/* Generated by tools/gm-seal.js — encrypted GM content. Do not edit by hand. */
window.GM_VAULT = {"v":1,"kdf":"PBKDF2-SHA256","iter":310000,"salt":"3yNXFzaZLrx99egebiFoRA==","iv":"qQiycdTaxXjd5j8g","ct":"EH/s9m/rxJvaZdpBS88OqA=="};
