# Groups (factions, orders, families, bands) for the Lore page's region galleries.
# Each group: site region, id, Portuguese name and description, and how cards join it:
#   champs  - champion names (English, as in Legends of Runeterra)
#   match   - regex over the card's English name
#   flavor  - regex over the card's English flavour text (optional, weaker hint)
#   uni     - titles of League Universe gallery pictures that belong here
# A card joins the first group that matches it; anything left in a region goes to its "Outros" bucket.

GROUPS = [
    # ---------------------------------------------------------------- Demacia
    dict(region='demacia', id='vanguard', name='Vanguarda Destemida',
         desc='A elite do exército demaciano, liderada por Garen. Soldados escolhidos a dedo que marcham na frente de cada batalha.',
         champs=['Garen'], match=r'Vanguard|Dauntless|Bannerman|Scrutinizing Sergeant',
         uni=['Guarda de Elite de Demacia', 'Elite Militar', 'Linha Guerreira e Guarda do Palácio', 'Armas Demacianas', 'Aço de Demacia', 'Equipamentos']),
    dict(region='demacia', id='crown', name='A Coroa e a Casa Lightshield',
         desc='A família real de Demacia. O rei Jarvan III morreu, e a sucessão do jovem Jarvan IV ainda divide as casas nobres.',
         champs=['Jarvan IV'], match=r'Jarvan|Honored Lord|Dawnspeakers', uni=['Príncipe Jarvan IV']),
    dict(region='demacia', id='crownguard', name='Casa Crownguard',
         desc='Uma das famílias mais tradicionais de Demacia, guardiã do trono. Dela vêm Garen e Lux, que esconde sua magia.',
         champs=['Lux', 'Lux: Illuminated'], match=r'Crownguard'),
    dict(region='demacia', id='laurent', name='Casa Laurent',
         desc='Família nobre de duelistas, famosa pela esgrima. Fiora governa a casa com a ponta da espada.',
         champs=['Fiora'], match=r'Laurent'),
    dict(region='demacia', id='durand', name='Escultores Durand',
         desc='Herdeiros do escultor que criou Galio. Moldam a petricita que protege Demacia da magia.',
         champs=['Galio'], match=r'Durand|Petricite (?!Hound|Stag|Charger|Broadwing)'),
    dict(region='demacia', id='mageseekers', name='Caça-Magos',
         desc='A ordem que persegue, prende e "protege" os magos de Demacia. Odiados por quem tem magia no sangue.',
         match=r'Mageseeker|Stony Suppressor|Penitent'),
    dict(region='demacia', id='rangers', name='Patrulheiros e Asa-Prateada',
         desc='Batedores e cavaleiros de rapina que vigiam as fronteiras. Quinn e sua águia Valor são os mais famosos.',
         champs=['Quinn'], match=r'Ranger|Silverwing|Swiftwing|Fleetfeather|Tracker|Valor|Jarro', uni=['Cavaleiro de Rapina']),
    dict(region='demacia', id='dragonguard', name='Guarda dos Dragões',
         desc='Os que servem ao lado de Shyvana e protegem (ou caçam) os dragões que ainda voam sobre Demacia.',
         champs=['Shyvana', 'Dragon Shyvana'], match=r'Dragonguard|Dragon Allegiant|Dragon Chow'),
    dict(region='demacia', id='illuminators', name='Iluminadores e devotos da Luz',
         desc='Clérigos e guerreiros que pregam a fé na luz e na ordem. Alguns caçam as trevas pelo mundo.',
         champs=['Vayne', 'Morgana'], match=r'Radiant|Illumin|Kingfisher', uni=['O Templo dos Arautos da Luz']),

    # ---------------------------------------------------------------- Noxus
    dict(region='noxus', id='trifarian', name='Legião Trifariana',
         desc='A força mais respeitada do exército noxiano, comandada por Darius. Disciplina, força e conquista.',
         champs=['Darius'], match=r'Trifarian|Legion(?! Deserter)|Iron Ballista|Battering Ram|Citybreaker|Imperial Demolitionist|Captain (Farron|Kalrix)',
         uni=['Os Bandos Guerreiros de Noxus', 'Força na Variedade', 'A Legião Trifariana', 'Armamento Noxiano', 'Armadura Noxiana', 'Machado de Darius', 'Artífices de Guerra']),
    dict(region='noxus', id='command', name='Alto Comando',
         desc='Swain e o Conselho Trifariano, que tomaram o império num golpe. Estrategistas, espiões e generais.',
         champs=['Swain'], match=r'Tactician|The Prefect|Incisive|Headmistress'),
    dict(region='noxus', id='blackrose', name='A Rosa Negra',
         desc='Uma sociedade secreta de magos que manipula Noxus nas sombras há séculos, liderada por LeBlanc.',
         champs=['LeBlanc'], match=r'Black Rose|Rose|Runeweaver|Rune Squire|Arachnoid|Spell Slinger|String-Puller'),
    dict(region='noxus', id='crimson', name='Círculo Carmesim',
         desc='Os hemomantes que seguem Vladimir e sua magia de sangue, entre banquetes e aristocratas.',
         champs=['Vladimir'], match=r'Crimson|Lady of Blood|Grave Physician'),
    dict(region='noxus', id='arena', name='Arenas e gladiadores',
         desc='Nas arenas de Noxus, glória vale tanto quanto ouro. Draven é o astro; muitos lutam para sair da obscuridade.',
         champs=['Draven', 'Samira'], match=r'Arena|Crowd|Draven|Reckoner|Gloryseeker|Dashing Dandy|Daring Demolisher|Shiraza|Kato'),
    dict(region='noxus', id='couteau', name='Família Du Couteau',
         desc='Assassinos de elite a serviço do império. Katarina é a lâmina mais conhecida da família.',
         champs=['Katarina'], match=r'Elegant Edge|Blade Squire'),
    dict(region='noxus', id='bastion', name='O Bastião Imortal',
         desc='A fortaleza de Mordekaiser, o antigo tirano que voltou dos mortos com seus cavaleiros e espectros.',
         champs=['Mordekaiser'], match=r'Revenant|Risen Rider|Fallen Rider|Wrathful Rider|Iron Harbinger', uni=['Camadas da História']),
    dict(region='noxus', id='gray', name='A Ordem Cinzenta',
         desc='Magos exilados que fugiram da Rosa Negra. Annie, filha de dois deles, carrega o urso Tibbers.',
         champs=['Annie'], match=r'Tibbers|Gray Apothecary'),
    dict(region='noxus', id='renegades', name='Desertores e mercenários',
         desc='Quem largou a Legião ou nunca entrou nela: mercenários, rebeldes e exilados como Riven.',
         champs=['Riven'], match=r'Deserter|Defector|Rebel|Mercenary'),

    # ---------------------------------------------------------------- Freljord
    dict(region='freljord', id='avarosan', name='Avarosanos',
         desc='A tribo de Ashe, que sonha unir o Freljord em paz. Arqueiros, guardas e caçadores das terras geladas.',
         champs=['Ashe', 'Tryndamere', 'Braum'], match=r'Avarosan|Hearthguard|Icevale Archer|Warden of the Tribes'),
    dict(region='freljord', id='winters-claw', name='Garra do Inverno',
         desc='A tribo guerreira de Sejuani. Saqueadores que acreditam que só os fortes merecem viver.',
         champs=['Sejuani'], match=r'Scar|Unscarred|Raider|Reaver|Wolfrider|Tuskraider|Ruthless',
         uni=['SAQUEADORES E RAPINADORES', 'ASSENTAMENTOS SAZONAIS', 'TOME O QUE PRECISAR', 'MONTADORES DE FERAS', 'CAÇANDO NAS PROFUNDEZAS', 'UMA TRIBO EM MARCHA']),
    dict(region='freljord', id='frostguard', name='Guarda Gélida e os Observadores',
         desc='Lissandra e seus seguidores guardam o Abismo Uivante. Em segredo, servem às entidades antigas presas sob o gelo.',
         champs=['Lissandra'], match=r'Frostguard|Thrall|Draklorn|Ice Pillar|Watcher|It That Stares|Icevale Cultist|Harbinger',
         uni=['O domínio da Bruxa Gélida', 'Os Draklorn', 'Contendo a escuridão', 'Olhos no Abismo', 'Pedras Mortis']),
    dict(region='freljord', id='ursine', name='Ursine (seguidores de Volibear)',
         desc='Guerreiros ursinos devotos do semideus da tempestade. Selvagens, livres e ferozes.',
         champs=['Volibear'], match=r'Ursine|Stormclaw|Thundersong|Sigil of the Storm'),
    dict(region='freljord', id='hearthblood', name='Ferreiros de Ornn',
         desc='Os que honram Ornn, o semideus da forja: ferreiros, artesãos e os fogos-vivos do Freljord.',
         champs=['Ornn'], match=r'Weaponsmith|Blacksmith|Artisan|Hearthblood|Ember Maiden|Flamecaller|Wrought'),
    dict(region='freljord', id='old-gods', name='Os Deuses Antigos e seus profetas',
         desc='Semideuses como Anivia, Volibear e Ornn, e os xamãs que ainda falam com eles e com os espíritos.',
         champs=['Anivia', 'Eggnivia', 'Udyr'], match=r'Old Ones|Valhir|Augur|Spiritwalker|Shaman|Seer|Scryer|Allseer|Spirit of the Ram|Wyrding|They Who Endure|She Who Wanders|Tusk Speaker'),
    dict(region='freljord', id='trolls', name='Trolls do Gelo',
         desc='Tribos de trolls reunidas em torno do Rei Trundle e de seu porrete de Gelo Verdadeiro.',
         champs=['Trundle'], match=r'Troll'),

    # ---------------------------------------------------------------- Ionia
    dict(region='ionia', id='kinkou', name='Ordem Kinkou',
         desc='Monges-ninjas que guardam o equilíbrio entre o reino espiritual e o mundo físico. Evitam extremos e se opõem à corrupção.',
         champs=['Shen', 'Kennen'], match=r'Kinkou', uni=['Os Kinkou']),
    dict(region='ionia', id='shadow', name='Ordem das Sombras',
         desc='Fundada por Zed, um ex-Kinkou. Acreditam que o pacifismo enfraqueceu Ionia e usam magia sombria e assassinato para defendê-la.',
         champs=['Zed'], match=r'^Shadow(?!tech)|Shadowblade|Shadowseer|Living Shadow|Ren Shadowblade|Shadow Assassin|The Shadow Assassin'),
    dict(region='ionia', id='navori', name='Irmandade Navori',
         desc='Rebeldes e foras-da-lei da província de Navori. Lutaram contra Noxus; hoje nem sempre se sabe de que lado estão.',
         champs=['Irelia'], match=r'Navori|Coastal Defender|Sacred Protector', uni=['O Placídio de Navori', 'A Grande Resistência']),
    dict(region='ionia', id='monks', name='Mestres e monastérios',
         desc='Monges, mestres de artes marciais e sábios espirituais, como Lee Sin, Master Yi e Karma.',
         champs=['Lee Sin', 'Master Yi', 'Karma'], match=r'Wuju|Monk|Disciple|Student|Mentor|Bingwen|Hirana|Doran|Jun, the Prodigy|Keeper of Masks|Old Timer',
         uni=['Os Grandes Monastérios']),
    dict(region='ionia', id='dragon', name='Os Seguidores do Dragão',
         desc='Guerreiros que tomam nomes das partes de um dragão (olho, garras, escamas, cauda) e evocam sua força.',
         match=r'of the Dragon|Dragoncaller'),
    dict(region='ionia', id='wanderers', name='Espadachins errantes',
         desc='Lâminas sem mestre que vagam com o vento, como os irmãos Yasuo e Yone.',
         champs=['Yasuo'], match=r'Yone|Windchaser|Windsinger|Windfarer|Blossoming Blade|Blade$|Zephyr'),
    dict(region='ionia', id='pit', name='O Fosso de Sett',
         desc='Lutas clandestinas, apostas e seguranças: o submundo que Sett, meio-vastaya, comanda com os punhos.',
         champs=['Sett'], match=r'Pit|Bout|Accountant|Mixologist|Stagehand'),
    dict(region='ionia', id='vastaya', name='Vastaya de Ionia',
         desc='Os povos-fera que vivem nas florestas e penhascos de Ionia, como Ahri e as tribos de Lhotlan.',
         champs=['Ahri'], match=r'Vastayan|Tail-Cloak|Sai\'nen|Yusari|Airis', uni=['Vastaya']),

    # ---------------------------------------------------------------- Bilgewater
    dict(region='bilgewater', id='buhru', name='Os Buhru (fé de Nagacáburos)',
         desc='O povo das Ilhas das Serpentes, devoto da Mãe Serpente. Illaoi é sua sacerdotisa mais forte.',
         champs=['Illaoi'], match=r'Buhru|Nagakabouros|Tentacle|Dedicant|Idol|Avatar of the Tides|Sea\'s Voice',
         uni=['Templo Buhru', 'As Ilhas das Serpentes', 'Nagacáburos']),
    dict(region='bilgewater', id='pirates', name='Piratas e tripulações',
         desc='As tripulações que fizeram a fama de Águas de Sentina. Gangplank foi o rei de todas elas.',
         champs=['Gangplank'], match=r'Buccaneer|Corsair|Deckhand|Powder|Plunder|Dreadway|Cutthroat|Petty Officer|Shelly|Helmsman|Lookout|Crusty|Babs|Navigator',
         uni=['Capitães e Tripulação', 'Canhões']),
    dict(region='bilgewater', id='bounty', name='Caçadores de recompensa e pistoleiros',
         desc='Gente que vive de cartazes de "procurado". Miss Fortune é a mais temida.',
         champs=['Miss Fortune'], match=r'Hired Gun|Sheriff|Bounty|Shellshocker|Five-Punch', uni=['Quadro de Recompensas', 'Bacamarte da Miss Fortune', 'Armas']),
    dict(region='bilgewater', id='hunters', name='Caçadores de monstros e açougueiros',
         desc='Os que caçam monstros marinhos e retalham as presas nas Docas da Matança. Pyke era um deles.',
         champs=['Pyke'], match=r'Jaull Hunters|Hunting Fleet|Razorscale Hunter|Butcher|Taskmaster|Harpoon|Dreg',
         uni=['Arpoeiros', 'Mestra do Arpão', 'Invocadores de Serpentes', 'Galpões de Matança', 'Baías de Entalhadura', 'Ossos do ofício']),
    dict(region='bilgewater', id='marai', name='Os Marai',
         desc='O povo-peixe vastaya dos recifes. Nami deixou as águas para buscar a Pedra da Lua.',
         champs=['Nami'], match=r'Marai|Tidedancer|Syren'),
    dict(region='bilgewater', id='gamblers', name='Jogadores e trapaceiros',
         desc='Cartas marcadas, dados viciados e mercado clandestino. Twisted Fate faz fortuna e inimigos em cada mesa.',
         champs=['Twisted Fate'], match=r'Gambler|Croupier|Pool Shark|Slotbot|Black Market|Swindler|Pocket Picker|Magician|Perfidious|Grifter'),

    # ---------------------------------------------------------------- Shadow Isles
    dict(region='shadow-isles', id='camavor', name='A corte de Viego (Camavor)',
         desc='O rei arruinado e os cavaleiros de sua antiga nação, Camavor, condenados com ele pela Ruína.',
         champs=['Viego', 'Kalista', 'Hecarim'], match=r'Camavor|Ledros|Deathless Knight|Duskrider|Spectral Rider|Iron Conquest',
         uni=['Hecarim']),
    dict(region='shadow-isles', id='sentinels', name='Sentinelas da Luz',
         desc='Uma antiga ordem que combate a Névoa Negra e os mortos. Senna, Lucian e Akshan levam sua luz pelo mundo.',
         champs=['Senna', 'Senna, Sentinel of Light', 'Lucian', 'Akshan'], match=r'Sentinel|Rekindler|Redeemed'),
    dict(region='shadow-isles', id='spider', name='Culto da Aranha',
         desc='Elise e seus devotos, que oferecem vidas a Vilemaw, a aranha gigante das Ilhas.',
         champs=['Elise', 'Spider Queen Elise'], match=r'Vilemaw|Cultist|Keeper of the Box'),
    dict(region='shadow-isles', id='helia', name='Os Heliatas',
         desc='Os sábios, escrivães e guardiões de Hélia, a cidade das Ilhas Abençoadas antes da Ruína.',
         match=r'Scribe|Chronicler|Archivist|Prodigy|Keeper|Islander|Catalogue|Hapless',
         uni=['Escrivão Eterno', 'Cidadãos das Ilhas das Bênçãos']),
    dict(region='shadow-isles', id='wardens', name='Thresh e as almas',
         desc='O carcereiro que coleciona almas numa lanterna, e os espíritos que guiam ou caçam os perdidos.',
         champs=['Thresh'], match=r'Soul Shepherd|Soulspinner|Warden', uni=['Thresh', 'Pastor de Almas']),

    # ---------------------------------------------------------------- Targon
    dict(region='targon', id='solari', name='Os Solari',
         desc='A fé do Sol, guardada por sacerdotes e guerreiros Ra\'Horak. Leona é o Aspecto do Sol.',
         champs=['Leona'], match=r'Solari|Sun|Daylight|Rahvun|Dawn',
         uni=['OS SOLARI', 'TEMPLO DO SOLSTÍCIO', 'SANTUÁRIO DE ORAÇÕES DOS SOLARI', 'ASTROLÁBIO DOURADO', 'ARMAS DOS RA’HORAK']),
    dict(region='targon', id='lunari', name='Os Lunari',
         desc='Os devotos da Lua, perseguidos pelos Solari como hereges. Diana e Aphelios lutam por eles.',
         champs=['Diana', 'Aphelios'], match=r'Lunari|Moon|Crescent|Dusk|Twilit|Eclipse',
         uni=['OS LUNARI', 'ESPERANÇA NO FUTURO', 'ARMAS PROIBIDAS']),
    dict(region='targon', id='aspects', name='Aspectos e Celestiais',
         desc='Mortais que escalaram a montanha e receberam um ser celestial, como Pantheon e Taric, e os próprios Celestiais.',
         champs=['Pantheon', 'Taric', 'Zoe', 'Soraka', 'Kayle', 'Aurelion Sol'], match=r'Aspect|Mihira|Celestial|Herald|Star Shepherd|Esmus|Iula|Arbiter'),
    dict(region='targon', id='rakkor', name='Os Rakkor e os peregrinos',
         desc='As tribos que vivem nas encostas do Monte Targon, e os alpinistas que tentam chegar ao topo.',
         match=r'Mountain|Sojourner|Pilgrim|Climber|Scholar|Stargazer|Scryer|Rumul|Mystic|Saga Seeker|Lawkeeper|Divine Clerk',
         uni=['CASA DOS RAKKOR', 'EM TORNO DA MONTANHA', 'OS RAKKOR', 'A VIDA ENTRE AS TRIBOS', 'OS GUERREIROS', 'TALHADO NA MONTANHA', 'VIDA DE PEREGRINO', 'EQUIPAMENTO DE ESCALADA', 'ITENS RELIGIOSOS', 'ARRANJO DO ZÊNITE', 'A DESPEDIDA', 'UMA JORNADA AO PICO DA MONTANHA', 'PADRÕES DOS MORTOS']),

    # ---------------------------------------------------------------- Shurima
    dict(region='shurima', id='empire', name='O Império e os Ascendidos',
         desc='Azir voltou e quer reconstruir o império. Ao seu lado e contra ele, os Ascendidos: Nasus, Renekton, Xerath.',
         champs=['Azir', 'Nasus', 'Renekton', 'Xerath'], match=r'Emperor|Sand Soldier|Golden|Sun Disc|Defenders|Devout|Hierophant|Council|Herald of the Magus|Reconstructor|Ascend|Dunekeeper|Sandcrafter|General of the Dunes|Inspiring Marshal|Priestess'),
    dict(region='shurima', id='darkin', name='Darkin e seus servos',
         desc='As armas vivas da guerra antiga e os cultistas que as libertam. Onde passam, deixam ruínas.',
         match=r'Baccai|Darkin|Xolaani|Acolyte|Altar of Blood|Ruinous'),
    dict(region='shurima', id='mercs', name='Mercenários e caçadores de tesouros',
         desc='Gente que vive das ruínas e dos contratos do deserto. Sivir é a mercenária mais cara de Shurima.',
         champs=['Sivir'], match=r'Vekauran|Treasure|Tomb-Raider|Ruin Runner|Profiteer|Acquisitioner|Poacher|Tycoon|Raz Bloodmane|Marauder|Bonecrusher|Merciless'),
    dict(region='shurima', id='nomads', name='Nômades, saqueadores e catadores',
         desc='Os que sobrevivem no deserto: tribos nômades, salteadores, catadores e os montadores de dormuns.',
         match=r'Nomad|Scout|Desert Naturalist|Rockbear Shepherd|Soothsayer|Sandseer',
         uni=['Saqueadores', 'Os Shakkal', 'Montadores de Dormuns', 'Catadores', 'No Topo dos Dormuns', 'Os Perdidos', 'Habitantes de classe alta da cidade', 'Habitantes de classe baixa da cidade']),
    dict(region='shurima', id='time', name='Os guardiões do tempo',
         desc='Zilean e os que estudam a magia do tempo, entre relógios, profecias e ruínas de Urtistan.',
         champs=['Zilean'], match=r'Clock|Chronomancer|Preservationist|Preservarium|Conservator'),
    dict(region='shurima', id='taliyah', name='Taliyah e os pedreiros',
         desc='A tecelã de pedras que deixou Noxus para proteger seu povo, e quem molda a terra do deserto.',
         champs=['Taliyah'], match=r'Stone|Sandstone|Rock'),

    # ---------------------------------------------------------------- Piltover
    dict(region='piltover', id='academy', name='Academia e inventores',
         desc='A Academia de Piltover reúne gênios, professores e aprendizes. Heimerdinger é o mais antigo deles.',
         champs=['Heimerdinger'], match=r'Academy|Academic|Professor|Prodigy|Archivist|Apprentice|Experimenter|Perfectionist|Mechanist|Funsmith|Acoustician|Adaptatron|Hextechnician',
         uni=['Oficina do Instituto Horológico', 'Oficinas', 'Vaido Violante']),
    dict(region='piltover', id='clans', name='Clãs mercantes',
         desc='As famílias ricas que governam Piltover pelo comércio: Ferros, Medarda, Kiramman e outras.',
         match=r'Ferros|Medarda|Kiramman|Albus|Financier|Benefactor',
         uni=['Jago Medarda', 'Insígnias de Clãs de Mercadores', 'Riqueza e Status']),
    dict(region='piltover', id='wardens', name='Vigias e investigadores',
         desc='A guarda de Piltover. Caitlyn, a xerife, e Vi, que trocou as ruas de Zaun pelo distintivo.',
         champs=['Caitlyn', 'Vi'], match=r'Sheriff|Officer|Patrol|Warden|Investigator|Sting|Justice Rider|Plaza Guardian', uni=['Vigias', 'Calibre Hexlyene de Vishlaa']),
    dict(region='piltover', id='hextech', name='Hextec e progresso',
         desc='Jayce e os inventores do hextec, a fusão de magia e tecnologia que mudou a Cidade do Progresso.',
         champs=['Jayce'], match=r'Hextech|Hexcore|Forge|Gearhead|Mk\d|Assembly Bot|Ballistic Bot',
         uni=['Hexarco de Ekalavya', 'Manoplas de Atlas', 'Artifício de Piltover', 'Bateria em Cubo Hextec', 'Hextec', 'Veículo Anelar', 'Armas Hextec', 'Conduíte de tubos pneumáticos']),
    dict(region='piltover', id='explorers', name='Exploradores e aeronautas',
         desc='Aventureiros, navegadores e pilotos de balão. Ezreal é o explorador mais famoso (e mais imprudente).',
         champs=['Ezreal'], match=r'Aeronaut|Cartographer|Explorer|Adventurer|Skycruiser|Mariner|Dropboarder|Cloudwinder|Castaway|Travelers'),

    # ---------------------------------------------------------------- Zaun
    dict(region='zaun', id='chempunks', name='Quimiopunks e gangues',
         desc='As gangues das ruas de Zaun, entre explosivos, gás e roubos. Jinx é a mais caótica de todas.',
         champs=['Jinx'], match=r'Chempunk|Urchin|Bouncer|Pickpocket|Gang|Shady|Flashbomb|Caustic|Henchmen|Boom', uni=['Punks Químicos', 'Assassinos de Aluguel', 'Pivetes do Sumidouro']),
    dict(region='zaun', id='barons', name='Barões químicos',
         desc='Os chefões que controlam Zaun por trás das fábricas e do brilho. Uma aliança frágil de conveniência.',
         match=r'Baron|Diva|Eminent|Mastermind|Corina',
         uni=['Baronesa Velveteen Lenare', 'Barões da Química', 'Barão Wencher Spindlow', 'Barão Saita Takeda', 'Barão Petrok Grime', 'Traficante de brilho']),
    dict(region='zaun', id='firelights', name='Fogos-Vivos (Ekko)',
         desc='O bando de Ekko, que protege o povo de Zaun e luta contra quem o explora.',
         champs=['Ekko'], match=r'Firelight|Dropboard'),
    dict(region='zaun', id='evolution', name='A Evolução Gloriosa',
         desc='Viktor e seus seguidores, que acreditam que a humanidade deve ser melhorada pela máquina.',
         champs=['Viktor'], match=r'Augment|Evolution|Clockling|Mechanized|Swapbot'),
    dict(region='zaun', id='sump', name='Trabalhadores do Sumidouro',
         desc='Mecânicos, catadores e encanadores dos níveis mais baixos e tóxicos da cidade.',
         match=r'Sump|Dredger|Chirean|Scavenger|Forge Worker|Scrap',
         uni=['Mecânico', 'Catador do Sumidouro', 'Respirador do Sumidouro com elmo de Cinza', 'Quimio-encanadores', 'Viginauta', 'Mensageiros do Calçadão', 'Residente do Calçadão', 'Pesquisador Quimtec', 'Mercador horticultor']),

    # ---------------------------------------------------------------- Bandle City
    dict(region='bandle', id='squads', name='Batedores e artilheiros',
         desc='Os yordles que protegem Bandópolis e saem para explorar: Teemo, Tristana e seus esquadrões.',
         champs=['Teemo', 'Tristana', 'Poppy'], match=r'Ranger|Gunner|Commando|Captain|Squire|Scout|Explorer|Newbie|Swole Scout|Grenadier|Cavalier'),
    dict(region='bandle', id='monks', name='Monges elementais',
         desc='Yordles que dominam o vento, o fogo e o trovão em monastérios escondidos. Kennen é um deles (e Kinkou).',
         match=r'Monk|Thunder Fist|Tornado|Masa|Rissu|Storm'),
    dict(region='bandle', id='inventors', name='Inventores e mechas',
         desc='Bombas, robôs e máquinas gigantes: Heimerdinger, Ziggs e Rumble não sabem parar quietos.',
         champs=['Ziggs', 'Rumble'], match=r'Mech|Chemist|Smith|Arsenal|Bomb|Blaster|Fix-Em|Inspector|Partsapalooza'),
    dict(region='bandle', id='gloom', name='Os sombrios',
         desc='Yordles que preferem a escuridão: Veigar, o mestre do mal (baixinho), e Vex, que acha tudo um saco.',
         champs=['Veigar', 'Vex', 'Grand Overseer Veigar'], match=r'Darkbulb|Gloom|Shadow|Evil|Imperfectionist'),
    dict(region='bandle', id='artists', name='Artistas e festeiros',
         desc='Músicos, pintores, contadores de histórias e organizadores de festa. Em Bandópolis, sempre há uma comemoração.',
         match=r'Painter|Balladeer|Tenor|Bass of Burden|Promoter|Mayor|Arena|Ava Achiever|Paparo|Tea Maker|Robemaker|Conchologist|Shark Trainer|Uncle'),
]

# Universe gallery pictures that are creatures (by title); everything else in a gallery is a place
# unless a group above claims it.
UNI_CREATURES = {
    'Rapinas Demacianas', 'Envergadura da Rapina', 'Ascensão do Ninho de Rapina', 'Cães-dragão', 'Basilisco',
    'FERAS DAS MONTANHAS', 'IBIK', 'TAMU', 'BÓLOR', 'Monstros das Profundezas', 'Bestas Marinhas',
    'Nadadores da Areia', 'Skallashi', 'Obstinados', 'Viúva dos Cantos Esquecidos', 'Igual Atrai Igual',
    'Morte Eterna', 'Além das Ilhas',
}
# Universe pictures that are about the region's people in general (they go to "Outros" in Grupos)
# English titles in the Portuguese Universe feed
UNI_TITLES = {
    'DOMAIN OF THE ICE WITCH': 'O domínio da Bruxa Gélida', 'THE DRAKLORN': 'Os Draklorn', 'HOLDING BACK THE DARKNESS': 'Contendo a escuridão',
    'EYES IN THE ABYSS': 'Olhos no Abismo', 'MORTIS STONES': 'Pedras Mortis',
}
UNI_PEOPLE = {
    'Culturalmente Inclusiva', 'Sangue Velho, Sangue Novo', 'Residentes da Cidade', 'Povos das tribos',
    'Mercador de frutas', 'Diversidade rica', 'Mercador de itens', 'O Barqueiro', 'Um Túmulo na Água',
    'As Aparências Enganam...', 'A Transmogrificação Visual de Heimerdinger', 'Mais Forte que a Vida ou a Morte',
    'Armas Tribais', 'Gelo Verdadeiro', 'Carabina Hex', 'Esofiltros reutilizáveis', 'Quimtec', 'Exofiltrador integral',
    'Nebulizador de gás do Sumidouro', 'Acordos hextec clandestinos', 'A filha de Setaka, ascendeu como Hierofante de Zuretta',
    'Iluminando a Cidade do Progresso', 'A Vida é uma Batalha', 'Interior da casa', 'Criando uma casa',
}
