// pt-BR: painel de Lore com os textos originais das notas de lore da campanha (em português), com a mesma estrutura
// de seções da versão em inglês (os ids são os mesmos, então os links da Terra Natal continuam funcionando).
(() => {
  'use strict';
  const MUNDO = 'O Mundo', LINHA = 'Linha do Tempo', REG = 'Regiões', POVOS = 'Povos';
  window.LORE_SECTIONS_PT = [
    { id: 'planet', group: MUNDO, title: 'O Planeta', body: `
      <p>Runeterra possui muitas características semelhantes às da Terra, mas dados sobre outros planetas desse sistema solar são desconhecidos atualmente. É um mundo naturalmente mágico, especialmente porque as <b>Runas Globais</b> são fundamentos do mundo, cuja ressonância atinge todos os seres, dando a eles capacidades extraordinárias.</p>
      <p>Os dois continentes em que focamos são <b>Valoran</b> e <b>Shurima</b>, onde estão situadas a maior parte das regiões, países, cidades-estados e outras formas de sociedade organizada de seres vivos, nem sempre humanos. Além desses dois continentes, existe <b>Ionia</b>, um continente insular, e alguns arquipélagos como <b>Águas de Sentina</b> e <b>as Ilhas das Sombras</b>.</p>
      <p>O que se conhece de Runeterra atualmente corresponde a <b>um sexto</b> de toda a sua extensão, em sua maioria no hemisfério norte do planeta. O restante desse mundo permanece praticamente desconhecido.</p>` },
    { id: 'runes', group: MUNDO, title: 'Runas Globais', body: `
      <p>Séculos atrás, foram redescobertos artefatos mágicos conhecidos como <b>Runas Globais</b>. Nas décadas seguintes, o conhecimento das Runas começou a se expandir à medida que mais delas eram descobertas. As mentes mais brilhantes do mundo estudaram os glifos ancestrais tentando determinar que poderes possuíam. Poucos conseguiam sequer entender a importância de suas origens ou o poder absoluto contido nelas.</p>
      <p>Alguns passaram a supor que as Runas eram parte integrante da criação da própria Runeterra. O primeiro uso desses artefatos misteriosos se provou catastrófico, pois modificaram completamente a paisagem de nações inteiras. A desconfiança cresceu rapidamente, conforme aqueles que conheciam as Runas imaginaram que tais "Poderes Criadores" pudessem ser usados como armas. Os conflitos posteriores relacionados a esses artefatos mágicos ficaram conhecidos como <b>as Guerras Rúnicas</b>.</p>
      <p>A guerra se alastrou por Runeterra. Os primeiros terrores das Guerras Rúnicas provocaram medo e agressão entre aqueles que agora percebiam o poder sob seu comando. Estudiosos dizem que um mago chamado <b>Ryze</b> e seu mestre <b>Tyrus</b> buscaram trancar essas Runas Globais longe do alcance dos homens, para a proteção de Runeterra. A localização atual dessas runas é um grande mistério, e há boatos de que Ryze ainda vive, continuando sua missão de mantê-las escondidas.</p>` },
    { id: 'realms', group: MUNDO, title: 'Reinos da Existência', body: `
      <h4>O Material</h4>
      <p>Também chamado de Reino Elemental, o Reino Material é o reino físico onde os elementos, as ideias e os espíritos se manifestam. É também onde se encontram as criaturas mortais, sujeitas ao sabor do tempo e predestinadas a ter uma breve história em meio à imensidão desse mundo. Sejam humanos, minotauros ou vastaya, essas espécies humanoides e inteligentes podem ser encontradas nas mais variadas expressões de existência.</p>
      <h4>O Espiritual</h4>
      <p>O Reino Espiritual se encontra em paralelo com o Reino Material e, em alguns pontos, pode se mesclar com ele, como no caso de <b>Ionia</b>, onde o véu que divide os dois reinos é mais fino e os espíritos influenciam diretamente a vida local, tanto a fauna quanto a flora, trazendo magia em abundância para o ambiente.</p>
      <h4>O Celestial</h4>
      <p>O Reino Celestial, muitas vezes chamado de <b>Cidade de Ouro e Prata</b>, é um reino além de Runeterra, cuja entrada pode ser encontrada no topo do <b>Monte Targon</b>, local que também serve de acesso das criaturas celestiais ao Reino Material. Esse reino é uma vastidão banhada em luz dourada durante o dia e estrelas cintilantes à noite.</p>
      <h4>O Vazio</h4>
      <p>O Vazio não é um lugar, mas sim o que existe <b>entre</b> os reinos. Não tem conexão com nenhum reino específico, porém pode se conectar ao Reino Material. Nesse lugar, o desejo de consumir é eterno, e ele é compartilhado por todas as criaturas que nascem ao se manifestar no mundo material; essas criaturas são conhecidas como <b>vastinatas</b>. Esse desejo de consumir se manifesta de maneiras diferentes em cada tribo de vastinatas: como alimento, como evolução pela assimilação ou como conhecimento pela desintegração.</p>` },
    { id: 'primordial', group: LINHA, title: 'A Era Primordial', body: `
      <p>É o vasto período que antecede toda a história registrada de Runeterra, abrangendo a criação do Reino Celestial, do Reino Espiritual e do Reino Físico. Antes da existência do tempo ou do espaço, havia apenas o nada do Vazio, lar de entidades sem forma conhecidas como <b>Observadores</b>.</p>
      <p>Essa vacuidade foi consumida pelo surgimento súbito da realidade, dando origem ao universo. Dentro desse universo, o "sopro da criação" moldou o Reino Celestial, onde <b>Aurelion Sol</b>, um grande dragão e pai dos cosmos, começou a preencher o vácuo, forjando as primeiras estrelas e constelações.</p>
      <p>O planeta Runeterra foi formado quando seres celestiais desconhecidos usaram as Runas Globais para tentar criar um reino separado do Celestial. Embora o trabalho tenha sido interrompido, as runas se espalharam pelo mundo e a criação inacabada formou os reinos físico e espiritual. O Reino Espiritual surgiu como um domínio de espíritos rico em magia primordial, separado do Reino Físico por um "véu" intangível.</p>
      <p>Nesta era surgiram diversos espíritos primordiais, como demônios, deuses, semideuses e yordles. A geografia do planeta foi moldada por muitos desses seres. Os primeiros seres de vida longa a surgir foram os <b>Dragões Terrestres</b>, que imitavam as formas dos dragões celestiais, e os clãs <b>Brackern</b>, criaturas parecidas com escorpiões. Por fim, os <b>humanos</b> surgiram e se espalharam pelo mundo, estabelecendo-se em regiões como Camavor e o Vorrijaard (hoje Freljord), onde passaram a adorar os semideuses e os seres que moldaram a terra. Outros seres, como yetis, os Vastayashai'rei, trolls e minotauros, também se formaram nessa era.</p>` },
    { id: 'titans', group: LINHA, title: '± 9000 AN: Guerra dos Titãs', body: `
      <p>Uma guerra terrível entre os mortais e uma raça de gigantes do céu assolou todo o continente insular hoje conhecido como Ionia. A vitória só chegou graças à interferência dos <b>Vastayashai'rei</b>, seres lendários e poderosos que habitam ao mesmo tempo os reinos material e espiritual.</p>
      <p>A guerra começou quando uma raça de <b>Titãs</b>, descritos como gigantes do céu, desceu sobre as Primeiras Terras (Ionia). Esses seres tinham tamanho e poder tão vastos que as forças mortais da época foram completamente subjugadas e incapazes de oferecer resistência eficaz. Os motivos exatos da descida e da agressão desses seres foram esquecidos ao longo dos milênios.</p>
      <p>Num estado de desespero absoluto para evitar a extinção, os mortais mais "iluminados" tomaram uma medida drástica: absorveram o poder do Reino Espiritual para dentro de si mesmos. Os humanos que absorveram essa magia tornaram-se os Vastayashai'rei, metamorfos imortais que usavam as forças da natureza como armas vivas contra os invasores.</p>
      <p>Após inúmeras batalhas brutais espalhadas por todo o arquipélago ioniano, os Vastayashai'rei saíram vitoriosos, levando a raça dos Titãs à extinção total. Com o fim da guerra, esses seres poderosos decidiram não governar os humanos comuns, mas viver entre eles em harmonia.</p>` },
    { id: 'sisters', group: LINHA, title: '± 8000 AN: Guerra das Três Irmãs', body: `
      <p>Nos tempos antigos, no Vorrijaard (hoje Freljord), nasceram três irmãs: <b>Avarosa</b>, <b>Serylda</b> e <b>Lissandra</b>. Nascidas num mundo de magia selvagem, as três dedicaram a vida a buscar uma maneira de controlar as poderosas forças mágicas do mundo. Serylda tentou comandar os céus acima delas, mas perdeu a voz. No primeiro crepúsculo, Avarosa encarou a escuridão retorcida sob o mundo e ficou surda com o seu vazio. Já Lissandra se opôs à magia selvagem do mundo, buscando controlar a magia natural dos próprios semideuses, e perdeu a visão num confronto com <b>Volibear</b>, deus do trovão. Ela fez pactos com seres do vazio chamados <b>Observadores</b> para adquirir magia e imortalidade.</p>
      <p>Surgiu um cisma entre as irmãs, que logo virou guerra. A batalha final aconteceu nos portões da cidadela de Lissandra, onde ela sacrificou muitos aliados e as próprias irmãs para sepultar os Observadores em <b>Gelo Verdadeiro</b>, e trabalhou com o deus da forja <b>Ornn</b> para construir uma "prisão" ao redor deles e evitar a destruição de Runeterra. Até hoje, a nação continua dividida em três facções, descendentes das três irmãs.</p>` },
    { id: 'migration', group: LINHA, title: '6000–5000 AN: Migração para o Oeste', body: `
      <p>Colonizadores dos continentes esquecidos do extremo leste chegaram ao litoral de Shurima e Valoran, trazendo consigo conhecimento e sabedoria milenares. Mais tarde, seus descendentes estariam entre os líderes das maiores civilizações que já habitaram Runeterra.</p>
      <h4>Fundação da Ilha de Buhru</h4>
      <p>Um grupo de humanos chamado <b>Buhru</b> se estabelece nas Ilhas da Serpente, onde passa a adorar o imensamente poderoso Deus Espírito, <b>Nagakabouros</b>, e, com o tempo, consegue canalizar o seu poder.</p>
      <h4>Fundação das Ilhas Abençoadas</h4>
      <p>Uma sociedade iluminada de estudiosos dedicados aos mistérios do mundo se forma nas <b>Ilhas Abençoadas</b> após um encontro com o espírito da natureza <b>Maokai</b>, que lhes deu conhecimento e a localização das abençoadas <b>Águas da Vida</b> como presente pelo respeito que tinham pela terra e pela sua magia.</p>
      <h4>Fundação de Ixtal</h4>
      <p>A <b>Arcologia Cardinal</b>, no que viria a ser Ixaocan, foi construída por <b>Skarner</b>, um Brackern, como presente para o povo de Ixtal. Seus habitantes se dedicam a dominar a magia elemental, e os mais brilhantes desses praticantes, junto com Skarner, se tornam a primeira geração dos <b>Yun Tal</b>.</p>
      <h4>Fundação de Faraj</h4>
      <p>A nação de <b>Faraj</b> foi fundada nos desertos do sudoeste do continente shurimane. Seu território acabou se estendendo para o leste até as encostas do Monte Targon, onde o povo Faraj fundou a cidade de <b>Nerimazeth</b>. Ao longo de mil anos, Nerimazeth cresceu em poder e influência, dando origem a <b>Shurima</b>, uma das primeiras nações de Faraj, com Nerimazeth como capital original.</p>
      <h4>Fundação das Tribos Targônicas</h4>
      <p>Mortais descobrem o Monte Targon e criam uma teocracia tribal centrada nos poderes celestiais que criaram a montanha, entrando em contato com os <b>Aspectos</b>.</p>
      <h4>Fundação de Oshra Va'Zaun</h4>
      <p>Um porto marítimo foi construído entre Valoran e o continente shurimane. Os habitantes desse porto passaram a venerar o espírito do vento, <b>Jan'ahrem</b> (uma antiga palavra shurimane que significa "guardiã"), pois ela sempre parecia aparecer em momentos de grande necessidade. Com o passar do tempo, ela passou a ser conhecida simplesmente como <b>Janna</b>.</p>
      <h4>Fundação do Reino de Icathia</h4>
      <p>A magocracia icathiana foi fundada na parte sul do continente shurimane sob o comando de seu primeiro <b>Rei-Mago</b>.</p>` },
    { id: 'golden-age', group: LINHA, title: '5000–2500 AN: A Era de Ouro de Shurima', body: `
      <p>Com a ajuda dos Aspectos de Targon, os antigos shurimanes construíram o primeiro <b>Disco Solar</b> em Nerimazeth para criar os primeiros <b>Ascendentes</b>, seres nobres adorados como deuses vivos.</p>
      <h4>3400 AN</h4>
      <p>Por algum motivo, o Disco Solar foi destruído. Um segundo Disco Solar, muito maior, foi erguido com a ajuda de magos de Ixtal. Dessa estrutura surgiu o <b>Oásis da Alvorada</b>, cujas águas mágicas transformaram o deserto e criaram o sistema do rio <b>Mãe da Vida</b>, que permitia sustentar uma população imensa.</p>
      <p>Nesse período, com seus guerreiros Ascendentes, Shurima se expandiu agressivamente, absorvendo nações como Ixtal e Oshra Va'Zaun. Shurima também conquistou Icathia depois que o rei <b>Axamuk</b> tentou, sem sucesso, apelar por uma coexistência pacífica.</p>` },
    { id: 'icathia', group: LINHA, title: '2500–2000 AN: Rebelião de Icathia e a libertação do Vazio', body: `
      <p>Icathia, então uma província sob o domínio do Império de Shurima, rebelou-se contra a opressão cultural e a tirania imperial.</p>
      <p>A rebelião começou oficialmente com a coroação de um novo Rei-Mago e a restauração da <b>Ordem Kohari</b>, cujos guerreiros chegaram a saquear assentamentos shurimanes e decapitar um Deus-Guerreiro em Bai-Zhek.</p>
      <p>Em resposta, Shurima enviou um exército liderado por dez <b>Deuses-Guerreiros</b>, entre eles <b>Aatrox</b> e <b>Setaka</b>. Durante o cerco às muralhas de Icathia, os magos rebeldes, num ato de desespero, libertaram o poder do <b>Vazio</b>. O poder tornou-se incontrolável, destruindo as torres de Icathia e corrompendo a terra para sempre.</p>` },
    { id: 'fall-shurima', group: LINHA, title: '2000 AN: A queda de Shurima', body: `
      <p>Após a queda de Icathia, começou uma guerra de séculos para conter a corrupção.</p>
      <p>Um mago elemental de Ixtal chamado <b>Ne'Zuk</b> criou uma fortaleza voadora de pedra chamada <b>Monólito</b> para combater o Vazio, mas ela acabou destruída.</p>
      <p>O Deus-Guerreiro <b>Horok</b> desferiu o primeiro golpe decisivo ao enfrentar o Vazio em suas profundezas com a <b>Lâmina do Éter</b>. Por fim, os Ascendentes conseguiram selar a <b>Grande Fenda</b> criada na Rebelião, e os que sobreviveram a essa guerra passaram a se chamar <b>Nascidos do Sol</b>.</p>
      <p>O imperador de Shurima nessa época, <b>Azir</b>, buscou realizar o ritual da Ascensão para se tornar um governante imortal e elevar Shurima a novos patamares. <b>Xerath</b>, escravo e amigo de infância de Azir, planejou secretamente usurpar o ritual. No momento crucial, Xerath empurrou Azir do pedestal, deixando o imperador ser consumido pelas chamas solares, e tomou o poder para si.</p>
      <p>Como o ritual não era destinado a Xerath, a energia celestial explodiu violentamente, obliterando a capital e fazendo o deserto engolir a cidade num único dia. O Disco Solar caiu e o império se fragmentou imediatamente.</p>
      <p>Outros dois Deuses-Guerreiros, <b>Nasus</b> e <b>Renekton</b>, voltaram às ruínas e confrontaram Xerath. Incapazes de destruí-lo, Renekton arrastou Xerath para a <b>Tumba dos Imperadores</b> e ordenou que Nasus selasse a porta, prendendo os dois num combate eterno.</p>` },
    { id: 'darkin', group: LINHA, title: '2000–550 AN: A Grande Guerra dos Darkin', body: `
      <p>Após a queda de Shurima, os Ascendentes restantes ficaram sem propósito e traumatizados pelas batalhas passadas contra o Vazio. Sem um imperador para contê-los, esses seres começaram a lutar entre si por poder e território. Dominaram uma magia de sangue proibida para remodelar seus corpos e foram amaldiçoados pelos mortais com o nome <b>Darkin</b> ("os caídos"). Os Darkin escravizaram nações inteiras e espalharam o caos por Runeterra.</p>
      <p>Uma celestial de Targon, a <b>Aspecto do Crepúsculo</b>, interveio e revelou aos mortais o segredo para derrotar os Darkin: aprisioná-los permanentemente dentro das próprias armas. As armas Darkin foram escondidas em diversos pontos de Runeterra e do Reino Espiritual para garantir que esses seres nunca mais fossem libertados.</p>` },
    { id: 'revenant', group: LINHA, title: '400–100 AN: O Reino do Revenã de Ferro', body: `
      <p>Séculos antes de sua ressurreição, ele era <b>Sahn-Uzal</b>, um rei bárbaro de Valoran que acreditava que a matança lhe garantiria um lugar de glória no salão dos deuses. Ao morrer, encontrou apenas um vazio cinzento e, movido pela fúria, recusou-se a desaparecer, aprendendo a língua dos mortos (<b>Ochnun</b>) para sussurrar aos vivos.</p>
      <p>Um grupo de magos o trouxe de volta para usá-lo como arma. Sahn-Uzal os enganou para que construíssem uma armadura de metal negro onde seu espírito ficou preso. Ele matou seus mestres, forjou sua maça com as almas deles e adotou o nome <b>Mordekaiser</b>. Ergueu o <b>Bastião Imortal</b>, uma fortaleza monumental, como símbolo do seu poder e repositório de conhecimentos proibidos sobre a morte e o reino espiritual. Comandava um exército de demônios e soldados caídos.</p>
      <p>Sua derrota foi orquestrada por uma feiticeira das tribos Noxii chamada <b>LeBlanc</b>, que vivia ao redor do Bastião, com a ajuda de um hemomante (mago sanguíneo) de Camavor chamado <b>Vladimir</b>. Eles tomaram sua fortaleza, que mais tarde se tornaria a capital de Noxus. Ao voltar ao reino da morte, Mordekaiser usou as almas de quem matou para construir o próprio reino eterno, <b>Mitna Rachnun</b>. Atualmente, ele segue acumulando poder em seu "Mundo do Além", preparando-se para um eventual retorno e seu reinado final sobre Runeterra.</p>` },
    { id: 'ruination', group: LINHA, title: '25 AN: A Ruína das Ilhas Abençoadas', body: `
      <p>Um desastre desencadeado pela obsessão do Rei <b>Viego</b> de Camavor (terras desconhecidas do extremo leste) em ressuscitar sua esposa, <b>Isolde</b>, que havia morrido atingida por uma adaga envenenada num atentado contra o rei. Viego enviou sua sobrinha e general, <b>Kalista</b>, em busca das lendárias <b>Águas da Vida</b>, localizadas na cidade de <b>Hélia</b>, nas Ilhas Abençoadas.</p>
      <p>Quando Viego chegou às ilhas com o corpo de Isolde e seu exército, os mestres de Hélia se recusaram a permitir o uso das águas curativas. Diante da recusa, Viego enlouqueceu e ordenou que a cidade fosse saqueada. Durante o caos, Kalista se recusou a atacar os habitantes inocentes e tentou proteger a cidade, mas foi traída e morta pelas costas por <b>Hecarim</b>, comandante da Ordem de Ferro do exército de Camavor.</p>
      <p>Um guardião local chamado <b>Erlok Grael</b>, em busca de poder pessoal, enganou Viego e o guiou até o <b>Poço das Eras</b>, afirmando que suas águas trariam a rainha de volta. Viego mergulhou o cadáver de Isolde no poço, mas o ritual teve um resultado terrível: a magia das águas interagiu de forma instável com uma Runa Global escondida sob o poço. Isolde voltou como um espectro em agonia e, em sua dor, tomou a espada de Viego e atravessou o coração do rei. O choque entre a magia da espada, a Runa Global e as águas desencadeou <b>a Ruína</b>, uma explosão massiva de energia mágica verde-azulada que varreu as ilhas.</p>
      <p>A explosão rasgou o véu entre os reinos material e espiritual, criando <b>a Névoa Negra</b>. As almas dos habitantes ficaram presas em tormento eterno, transformando-se em espectros. As ilhas tornaram-se um lugar amaldiçoado, hoje conhecido como <b>Ilhas das Sombras</b>, enquanto o Reino de Camavor entrou em declínio total após perder sua monarquia.</p>` },
    { id: 'rune-wars', group: LINHA, title: '25–3 AN: As Guerras Rúnicas', body: `
      <p>Após a ruína de Hélia, os artefatos mágicos perigosos que eram protegidos nas Ilhas Abençoadas ficaram sem supervisão e se espalharam pelo mundo. Seguiu-se uma série de conflitos globais devastadores, em que os mortais de Runeterra usaram as Runas Globais como armas de guerra. Esses conflitos foram tão brutais que apagaram diversas civilizações, alteraram massas de terra e eliminaram grande parte da história registrada, mergulhando o mundo num declínio civilizacional e num estilo de vida primitivo.</p>
      <p>O primeiro ataque devastador documentado aconteceu quando o mago <b>Tyrus</b> e seu aprendiz <b>Ryze</b> tentaram mediar a paz entre duas nações Noxii rivais. O encontro terminou com a destruição total da vila de <b>Khom</b> e seus arredores pelo poder de duas Runas Globais, dando início oficial às guerras em larga escala. Durante os combates, o uso de magia extrema causou catástrofes como a destruição dos <b>Jardins de Zyr</b> na selva de Shurima, que ficaram sem vida por séculos. Cabalas de magos-guerreiros dominaram o reino espiritual com magia das sombras, o que deu origem ao demônio <b>Nocturne</b>. Outras entidades, como <b>Evelynn</b>, se alimentaram do sofrimento humano nesse período e se transformaram em demônios poderosos. Ao ver seu mestre Tyrus tentar usar o poder das runas para fins próprios, Ryze foi forçado a matá-lo. Jurou nunca usar uma Runa Global e dedicou a vida a encontrá-las e escondê-las para evitar a aniquilação do mundo.</p>` },
    { id: 'resurgence', group: LINHA, title: '0–789 DN: O Ressurgimento da Civilização', body: `
      <p>Começa então um período histórico em que as principais nações modernas de Runeterra passam a emergir e se consolidar após os cataclismos das Guerras Rúnicas.</p>
      <h4>Noxus (0–349 DN)</h4>
      <p>As tribos Noxii buscaram refúgio dentro do Bastião Imortal. Com a ajuda da <b>Rosa Negra</b>, grupo formado por LeBlanc e Vladimir, conseguiram repelir a devastação mágica e, ao fim das guerras, unificaram-se como o império de <b>Noxus</b>. Aqui se marca o <b>ano 0 do calendário noxiano</b>.</p>
      <p>Em 349 DN, Noxus tornou-se oficialmente uma potência imperial. As casas nobres juraram unificar todas as nações sob uma única bandeira e elegeram o primeiro <b>Grande General</b> para liderar suas conquistas, iniciando anexações forçadas como a de Drakkengate.</p>
      <h4>Demacia (0–292 DN)</h4>
      <p>A nação foi fundada por refugiados das Guerras Rúnicas liderados pelo campeão <b>Orlon</b>. Eles descobriram uma floresta de <b>petricita</b> que anulava a magia e ali fundaram a primeira cidade, <b>Zeffira</b>.</p>
      <p>No auge das Guerras Rúnicas, um casal (Mihira e Kilam) escalou o Monte Targon para escapar da guerra. Mihira foi escolhida pelo <b>Aspecto da Justiça</b>, e suas filhas gêmeas, <b>Kayle</b> e <b>Morgana</b>, nasceram sob essa influência divina. Durante os primeiros séculos, as irmãs atuaram como protetoras de Demacia. No entanto, um conflito ideológico e a morte do pai levaram a uma batalha devastadora que deixou Zeffira em ruínas, e as duas desapareceram.</p>
      <p>Em 292 DN, a capital foi transferida para a <b>Grande Cidade</b> e <b>Argostan</b> foi coroado o primeiro rei. Demacia foi declarada um santuário eterno contra a magia, e o escultor <b>Durand</b> criou <b>Galio</b>, o colosso de petricita, para a proteção militar.</p>
      <h4>Piltover e Zaun (772–789 DN)</h4>
      <p>As tentativas de construir os <b>Portões Solares</b>, uma passagem marítima entre Valoran e Shurima, causaram terremotos catastróficos. Grandes partes da antiga cidade portuária de Oshra Va'Zaun afundaram em cavernas profundas e gases tóxicos foram liberados; a deusa Jan'ahrem, hoje conhecida como <b>Janna</b>, interveio para salvar milhares de cidadãos. Após décadas de reconstrução, a nova e rica elite comercial ergueu um distrito sobre o rio Pilt e o batizou de <b>Piltover</b> ("sobre o Pilt"). A abertura dos Portões Solares trouxe riqueza imensa e permitiu que Noxus consolidasse recursos pelo mar.</p>
      <h4>Águas de Sentina (787 DN)</h4>
      <p>Missionários dos nativos Buhru permitiram que imigrantes e caçadores de fortuna (chamados <b>paylangi</b>) se estabelecessem nas baías das Ilhas da Serpente, dando origem a uma cidade portuária caótica e próspera.</p>
      <h4>Nazumah (498 DN)</h4>
      <p>No sul de Shurima, um grupo de pessoas fundou uma sociedade de caçadores de monstros ao redor de um oásis, dominando as feras gigantes que assolavam a região havia anos.</p>` },
    { id: 'demacia-noxus-war', group: LINHA, title: '892–895 DN: A Primeira Guerra Demaciano-Noxiana', body: `
      <p>Após séculos anexando territórios no centro de Valoran, as frentes de guerra noxianas marcharam em direção à costa oeste do continente. Ali encontraram resistência pela primeira vez, ao enfrentar o exército de Demacia, cujos soldados eram especializados em defesa. A expansão de Noxus foi interrompida pela primeira vez em sua história.</p>
      <p>Superados em estratégia, os noxianos foram empurrados de volta para o sudeste, buscando refúgio atrás das muralhas do assentamento fortificado de <b>Hvardis</b>. O comandante local estava disposto a deixar os demacianos partirem sem novos ataques, o que enfureceu o general noxiano <b>Sion</b>, que havia voltado de uma campanha nas Montanhas Argentadas para retomar o controle da situação. Sion executou o comandante de Hvardis por sua hesitação e liderou uma carga contra as forças demacianas. Mesmo em desvantagem numérica e atravessado por diversas armas inimigas, Sion conseguiu alcançar o Rei <b>Jarvan I</b> de Demacia. Estrangulou o rei até a morte com as próprias mãos, morrendo apenas quando o monarca parou de respirar.</p>
      <p>Com a morte do rei, o exército demaciano recuou para dentro de suas fronteiras. Sion foi enterrado como herói nacional num grande monumento em Noxus. No entanto, a guerra resultou no declínio da influência noxiana por cerca de 50 anos, período em que Demacia libertou várias nações do centro de Valoran que estavam sob domínio noxiano.</p>` },
    { id: 'present', group: LINHA, title: 'A história recente e os tempos atuais', body: `
      <p>A história recente de Runeterra compreende a segunda metade do décimo século após a fundação de Noxus, sendo o ano <b>994 DN</b> em diante considerado o presente, onde acontece a história do nosso RPG. É o período em que se desenrola a maioria das histórias dos campeões canônicos, marcado por agitações políticas, pelo retorno de deuses antigos e por ameaças globais.</p>
      <div class="cs-callout"><b>Para criar seu personagem</b>, consulte principalmente o trecho das Guerras Rúnicas até aqui, que reúne os pontos mais importantes da lore. Se faltar alguma informação, procure na seção de Regiões ou até no site oficial do <em>Universo de League of Legends</em>. Aqui vai um breve resumo:</div>
      <h4>Noxus</h4>
      <p>Em 989, após a desastrosa primeira invasão de Ionia e a corrupção do General Darkwill, <b>Jericho Swain</b> orquestrou um golpe político que abalou os alicerces do império. Ele derrubou Darkwill e estabeleceu o <b>Trifarix</b>, um conselho de três líderes que representam os princípios da força. Enquanto isso, a Rosa Negra continua operando nas sombras, com espiões infiltrados em todas as nações.</p>
      <h4>Demacia</h4>
      <p>Após séculos de perseguição aos magos, a tensão explodiu na <b>Grande Rebelião dos Magos</b> de 994, liderada por <b>Sylas</b>, que mergulhou a nação numa guerra civil que continua até hoje.</p>
      <h4>Shurima</h4>
      <p>Após milênios sob as areias, o imperador <b>Azir</b> ressuscitou em 989, restaurando o Disco Solar e a capital de Shurima. Isso desencadeou uma luta pelo domínio do deserto contra o liberto <b>Xerath</b>, cujos cultistas começaram a atacar assentamentos shurimanes em todo o continente.</p>
      <h4>Ionia</h4>
      <p>Continua uma terra isolada, recuperando-se da invasão noxiana, que gerou uma revolução cultural e política. Lá está a <b>Ordem Kinkou</b>, uma das organizações mais antigas de Ionia, dedicada a manter o equilíbrio entre os mundos material e espiritual. Recentemente, um ex-ninja da ordem Kinkou, <b>Zed</b>, formou a <b>Ordem das Sombras</b> para se defender de Noxus de forma mais violenta e brutal, indo contra os ensinamentos Kinkou.</p>
      <h4>Freljord</h4>
      <p>Nos últimos anos, o Freljord tem sido definido por uma luta desesperada pela sobrevivência, por conflitos tribais e pelo ressurgimento aterrorizante de antigos semideuses. É liderado por três grandes tribos: os <b>Avarosianos</b> (seguidores da mãe-de-guerra <b>Ashe</b>, descendente de Avarosa), a <b>Garra do Inverno</b> (seguidores da mãe-de-guerra <b>Sejuani</b>, descendente de Serylda) e a <b>Guarda Gélida</b> (a ordem de Lissandra), que vivem em batalha constante.</p>
      <p>Os Observadores do Vazio estão mostrando sinais de despertar. Os <b>Ursine</b>, seguidores do deus Volibear, disputam território com a Garra do Inverno. Os <b>fogos-vivos</b>, seguidores de Ornn, continuam reclusos perto da montanha desse deus. Os <b>yetis</b>, outrora abençoados por Anivia com o domínio do Gelo Verdadeiro, foram reduzidos a criaturas ferais.</p>` },
    { id: 'r-bilgewater', region: 'bilgewater', group: REG, title: 'Águas de Sentina', body: `
      <p>Águas de Sentina é um refúgio para contrabandistas, saqueadores e pessoas sem escrúpulos, onde fortunas são feitas e ambições destruídas num piscar de olhos. Para quem foge da justiça, de dívidas ou de perseguição, é uma cidade de recomeços; ninguém nas ruas sinuosas de Águas de Sentina se importa com o seu passado. É um caldeirão de culturas, raças e crenças, fervilhando de atividade a qualquer hora do dia ou da noite.</p>
      <p>Embora incrivelmente perigosa, Águas de Sentina também é repleta de oportunidades, livre das amarras do governo, da regulamentação e das restrições morais. Se você tiver dinheiro, quase tudo pode ser comprado em Águas de Sentina, desde tecnologia hextec proibida até o favor dos chefões do crime locais. Contudo, ao amanhecer, os incautos aparecem boiando no porto, com as bolsas vazias e as gargantas cortadas.</p>` },
    { id: 'r-bandle', region: 'bandle', group: REG, title: 'Bandópolis', body: `
      <p>Há opiniões divergentes sobre a localização exata do lar dos yordles, embora alguns mortais afirmem ter viajado por caminhos invisíveis até uma terra de encantamento curioso além do reino material. Eles falam de um lugar de magia desenfreada, onde os temerários podem se perder em meio a inúmeras maravilhas e acabar imersos num sonho…</p>
      <p>Em Bandópolis, dizem, todas as sensações são aguçadas para quem não é yordle. As cores são mais vibrantes. A comida e a bebida embriagam os sentidos por anos e, uma vez provadas, jamais são esquecidas. A luz do sol é eternamente dourada, as águas são cristalinas e cada colheita traz farta abundância. Talvez algumas dessas afirmações sejam verdadeiras, ou talvez nenhuma, já que nenhum contador de histórias parece concordar sobre o que realmente viu.</p>
      <p>Só uma coisa é certa: a natureza atemporal de Bandópolis e de seus habitantes. Isso talvez explique por que os mortais que conseguem voltar muitas vezes parecem ter envelhecido muito, enquanto tantos outros jamais retornam.</p>` },
    { id: 'r-demacia', region: 'demacia', group: REG, title: 'Demacia', body: `
      <p>Um reino forte e regido pela lei, com uma história militar prestigiosa, Demacia sempre teve como valores supremos os ideais de justiça, honra e dever, e seu povo se orgulha imensamente de sua herança cultural. Mas, apesar desses princípios nobres, essa nação, em grande parte autossuficiente, tornou-se cada vez mais insular e isolacionista nos últimos séculos. Agora, Demacia é um reino em turbulência.</p>
      <p>A antiga capital, <b>Zeffira</b>, foi fundada como refúgio contra a feitiçaria após o pesadelo das Guerras Rúnicas e construída sobre o enigma da <b>petricita</b>, uma peculiar pedra branca que atenua a energia mágica. Após sua queda, Demacia transferiu a capital para a Grande Cidade de Demacia. É de lá que a família real há muito cuida da defesa das cidades e vilarejos periféricos, das terras agrícolas, das florestas e das montanhas ricas em minérios.</p>
      <p>No entanto, após a morte repentina do Rei <b>Jarvan III</b>, as outras famílias nobres ainda não aprovaram a sucessão de seu único herdeiro, o jovem Príncipe <b>Jarvan IV</b>, ao trono.</p>
      <p>Quem vive além das fronteiras fortemente vigiadas é visto com crescente desconfiança, e muitos antigos aliados começaram a buscar proteção em outros lugares nestes tempos incertos. Alguns ousam sussurrar que a era de ouro de Demacia chegou ao fim e que, a menos que seu povo esteja disposto a se adaptar a um mundo em transformação (e muitos o julgam simplesmente incapaz disso), o declínio do reino pode ser inevitável.</p>
      <p>E nem toda a petricita da terra protegerá Demacia de si mesma.</p>` },
    { id: 'r-shadow-isles', region: 'shadow-isles', group: REG, title: 'Ilhas das Sombras', body: `
      <p>A terra hoje conhecida como Ilhas das Sombras já foi um reino belo, mas foi devastada por um cataclismo mágico. Uma <b>Névoa Negra</b> envolve permanentemente as ilhas, e a própria terra está contaminada, corrompida por forças malignas. Os seres vivos que habitam as Ilhas das Sombras têm sua força vital drenada lentamente, o que, por sua vez, atrai os espíritos insaciáveis e predadores dos mortos.</p>
      <p>Quem perece na Névoa Negra é condenado a assombrar esta terra melancólica pela eternidade. Pior ainda, o poder das Ilhas das Sombras se fortalece a cada ano, permitindo que as sombras dos mortos-vivos expandam seu alcance e ceifem almas por toda Runeterra.</p>` },
    { id: 'r-ionia', region: 'ionia', group: REG, title: 'Ionia', body: `
      <p>Ionia, chamada de <b>Primeiras Terras</b> na nomenclatura original vastayana, é uma terra de beleza intocada e magia natural. Seus habitantes, vivendo em assentamentos dispersos por este vasto arquipélago, são um povo espiritual que busca viver em harmonia e equilíbrio com o mundo. Existem muitas ordens e seitas em Ionia, cada uma seguindo seus próprios caminhos e ideais (frequentemente conflitantes).</p>
      <p>Autossuficiente e isolacionista, Ionia permaneceu em grande parte neutra nas guerras que devastaram Valoran ao longo dos séculos, até ser invadida por Noxus. Esse conflito brutal e a ocupação forçaram Ionia a reavaliar seu lugar no mundo. Como vai reagir, e que caminho vai seguir, ainda é incerto; contudo, a animosidade contra Noxus levou à militarização e ao vigilantismo, e a sede pelas artes das trevas está em ascensão.</p>` },
    { id: 'r-ixtal', region: 'ixtal', group: REG, title: 'Ixtal', body: `
      <p>Reconhecida por seu domínio da magia elemental, Ixtal foi uma das primeiras nações independentes a se unir ao império shurimane. Na verdade, a cultura ixtali é muito mais antiga. Ela fez parte da grande diáspora para o oeste que deu origem a civilizações como os Buhru, a magnífica Hélia e os ascetas de Targon, e é provável que tenha tido um papel significativo na criação dos primeiros Ascendentes.</p>
      <p>Mas os magos de Ixtal sobreviveram ao Vazio e, mais tarde, aos Darkin, afastando-se dos vizinhos e atraindo a natureza selvagem ao redor como um escudo. Embora muito já tivesse se perdido, eles se comprometeram a preservar o pouco que restava…</p>
      <p>Agora, isolada nas profundezas da selva há milhares de anos, a sofisticada cidade-arcologia de <b>Ixaocan</b> permanece praticamente livre de influências externas. Tendo testemunhado de longe a ruína das Ilhas Abençoadas e as Guerras Rúnicas que se seguiram, os ixtali consideram todas as outras facções de Runeterra usurpadoras e impostoras, e usam sua poderosa magia para manter qualquer intruso à distância.</p>` },
    { id: 'r-nazumah', region: 'nazumah', group: REG, title: 'Nazumah', body: `
      <p>Nazumah é uma terra de guerreiros e caçadores valorosos, acostumados a caçar criaturas gigantes e poderosas. Com uma cultura rica e colorida, que parece celebrar a liberdade sem fim a cada dia, seu povo nunca esquece a liberdade que conquistou da opressão dos chamados "deuses guerreiros", à custa de muita luta.</p>
      <p>Entre os nazumitas é normal encontrar diversas etnias e culturas que fugiram da Guerra Darkin, com gente de várias regiões em busca da liberdade que o país proporciona, ou apenas atrás das novidades mais exóticas dos seus mercados.</p>
      <p>A relação de Nazumah com os outros shurimanes tende a ser pacífica e amistosa, desde que não haja indício de que sirvam ou estejam ligados a um Ascendente; isso pode mudar rapidamente quando se constata o contrário. Se perceberem algum sinal de escravidão ou servidão forçada, podem tomar como meta pessoal ajudar esse "irmão das areias" a se libertar.</p>
      <p>Muitos dos produtos mais importantes de Shurima, como os do mercado de Medumarca, circulam primeiro pelos mercados de Nazumah, onde são negociados com muita habilidade e esperteza. Tentar passar a perna num comerciante nazumita não é boa ideia, pois pode até significar o banimento do país.</p>` },
    { id: 'r-freljord', region: 'freljord', group: REG, title: 'Freljord', body: `
      <p>O Freljord é uma terra árida e implacável. Orgulhoso e ferozmente independente, seu povo nasce guerreiro, com uma forte cultura de pilhagem.</p>
      <p>Embora existam muitas tribos no Freljord, as linhas de batalha estão sendo traçadas numa guerra civil entre três facções que vai determinar o futuro de todas elas. Uma tribo honra inabalavelmente as tradições que garantiram sua sobrevivência; outra segue o sonho de um futuro unido, como previsto por uma jovem idealista; e a terceira venera o poder de um ser enigmático. O Freljord também é o único lugar onde se pode encontrar <b>Gelo Verdadeiro</b>.</p>` },
    { id: 'r-noxus', region: 'noxus', group: REG, title: 'Noxus', body: `
      <p>Noxus é um império poderoso com uma reputação temível. Para quem está além de suas fronteiras, Noxus é brutal, expansionista e ameaçadora, mas quem olha além da fachada belicosa vê uma sociedade excepcionalmente inclusiva, onde a força e os talentos do povo são respeitados e cultivados.</p>
      <p>Seu povo já foi uma cultura feroz de saqueadores, até invadir a antiga cidade que hoje fica no coração do império. Ameaçados por todos os lados, levaram a luta agressivamente aos inimigos, expandindo as fronteiras a cada ano que passava. Essa luta pela sobrevivência fez dos noxianos um povo profundamente orgulhoso, que valoriza a força acima de tudo, ainda que essa força possa se manifestar de muitas formas diferentes.</p>
      <p>Qualquer um pode ascender a uma posição de poder e respeito em Noxus se demonstrar a aptidão necessária, independentemente de posição social, origem, terra natal ou riqueza.</p>` },
    { id: 'r-piltover', region: 'piltover', group: REG, title: 'Piltover', body: `
      <p>Piltover, também conhecida como <b>a Cidade do Progresso</b>, é uma cidade próspera e progressista cujo poder e influência estão em ascensão. É o centro cultural de Valoran, onde arte, artesanato, comércio e inovação caminham lado a lado. Seu poder não vem da força militar, mas dos motores do comércio e do pensamento visionário.</p>
      <p>Situada nos penhascos acima do distrito de Zaun e com vista para o oceano, vê frotas de navios atravessarem seus gigantescos portões marítimos, trazendo mercadorias do mundo todo. A riqueza gerada impulsionou um crescimento sem precedentes. Piltover se reinventou, e continua se reinventando, como uma cidade onde fortunas podem ser feitas e sonhos podem ser realizados. Clãs mercantes em ascensão financiam as empreitadas mais incríveis: grandes extravagâncias artísticas, pesquisas esotéricas em <b>hextecnologia</b> e monumentos arquitetônicos que simbolizam seu poder.</p>
      <p>Com cada vez mais inventores explorando o conhecimento emergente da hextecnologia, Piltover se tornou um polo de atração para os artesãos mais habilidosos do mundo.</p>` },
    { id: 'r-zaun', region: 'zaun', group: REG, title: 'Zaun', body: `
      <p>Zaun, também conhecida como <b>a Cidade de Ferro e Vidro</b>, é um grande distrito subterrâneo situado nos profundos cânions e vales que atravessam Piltover. A pouca luz que chega lá embaixo é filtrada pela fumaça que vaza dos emaranhados de tubulações corroídas e refletida pelos vitrais de sua arquitetura industrial. Zaun e Piltover já foram unidas, mas hoje são sociedades separadas, embora simbióticas.</p>
      <p>Apesar de existir num crepúsculo perpétuo e esfumaçado, Zaun prospera: seu povo é vibrante e sua cultura, rica. A riqueza de Piltover permitiu que Zaun se desenvolvesse em paralelo, um reflexo sombrio da cidade de cima. Muitas das mercadorias que chegam a Piltover acabam nos mercados negros de Zaun, e inventores de hextecnologia que acham rígidas demais as restrições da cidade de cima costumam ter suas pesquisas perigosas bem-vindas em Zaun.</p>
      <p>O desenvolvimento desenfreado de tecnologias voláteis e a indústria imprudente deixaram vastas áreas de Zaun poluídas e perigosas. Nas partes mais baixas da cidade, rios de esgoto tóxico ficam estagnados, mas mesmo ali as pessoas encontram um jeito de sobreviver e prosperar.</p>` },
    { id: 'r-shurima', region: 'shurima', group: REG, title: 'Shurima', body: `
      <p>O império de Shurima já foi uma civilização próspera que se estendia por um vasto deserto. Após uma era de crescimento e prosperidade, a queda de sua reluzente capital deixou o império em ruínas. Ao longo de milênios, as histórias da gloriosa cidade de Shurima se tornaram mito e religião entre os descendentes dos sobreviventes dispersos.</p>
      <p>A maioria dos habitantes nômades de Shurima busca o sustento básico numa terra implacável. Alguns defendem pequenos postos avançados construídos ao redor dos poucos oásis. Outros procuram riquezas enterradas entre as ruínas do império caído, ou aceitam trabalho mercenário, recebendo ouro por seus feitos antes de desaparecerem de volta nas areias. Agora, as tribos estão agitadas por sussurros vindos do coração do deserto: <b>a capital de Shurima ressuscitou</b>.</p>` },
    { id: 'r-targon', region: 'targon', group: REG, title: 'Targon', body: `
      <p>Como qualquer lugar mítico, o Monte Targon é um farol para sonhadores, loucos e aventureiros. Região montanhosa e pouco habitada a oeste de Shurima, Targon ostenta o pico mais alto de Runeterra. Longe da civilização, o Monte Targon é praticamente inacessível, exceto para os peregrinos mais determinados, movidos por um anseio profundo de alcançar o cume. Os poucos corajosos que sobrevivem à árdua jornada até a base da montanha titânica encontram um céu cintilante de corpos celestes: o sol e as luas, mas também constelações, planetas, cometas flamejantes riscando a escuridão e auspiciosos alinhamentos de estrelas. Eles voltam assombrados e vazios, ou transformados a ponto de ficarem irreconhecíveis.</p>
      <p>Os habitantes da base da montanha acreditam que esses corpos celestes sejam aspectos de seres estelares há muito desaparecidos, criaturas poderosas e ancestrais numa escala que transcende a compreensão humana. No entanto, o Monte Targon é simplesmente uma porta de entrada para o <b>Reino Celestial</b>, e seria um erro atribuir muito de sensibilidades, moral ou preocupações mortais ao que existe além da montanha.</p>` },
    { id: 'r-void', region: 'void', group: REG, title: 'O Vazio', body: `
      <p>O Vazio é o "Reino do Nada" que se encontra além do Reino Material.</p>
      <p>É também uma manifestação desse nada incognoscível: uma força de fome insaciável, à espera através dos éons até que seus mestres, os misteriosos <b>Observadores</b>, marquem o momento final da destruição.</p>
      <p>Ser um mortal tocado pelo poder do Vazio é sofrer um vislumbre agonizante da irrealidade eterna, suficiente para destruir até a mente mais forte. Os habitantes do próprio reino do Vazio são criaturas-construções, muitas vezes de consciência limitada, mas incumbidas de um propósito singular: levar o esquecimento total a Runeterra.</p>` },
    { id: 'andarilhos', gallery: 'runeterra', group: REG, title: 'Outras', body: `
      <p>Nem tudo pertence a uma região só. Há quem vague pelo mundo inteiro, como o Bardo, Ryze ou o Jax; há armas que já passaram por muitas mãos, como os Darkin; e há poderes que nenhuma nação controla, como as Runas Globais.</p>
      <p>Aqui também ficam <b>Camavor</b>, o reino extinto de Viego, e <b>Kathkan</b>, sua vizinha e antiga rival, ambos num continente a leste que o mapa de Valoran não mostra.</p>
      <p>Use estas figuras como encontros raros, lendas contadas ao pé da fogueira ou o motivo que tirou seu campeão de casa.</p>` },
    { id: 'races', group: POVOS, title: 'Raças', body: `
      <p>Os povos jogáveis de Runeterra. Cada verbete diz onde eles vivem, exemplos conhecidos e quais escolhas do criador combinam com eles. As raças não têm regras próprias neste sistema: sua raça se expressa pela Origem, pela Fonte de Poder, pelos poderes e pelos princípios.</p>
      ${[
        ['Humano', 'O povo mais difundido de Runeterra, presente em todas as regiões, do Freljord a Shurima. Os humanos surgiram no fim da Era Primordial e se espalharam pelo mundo, fundando as nações que moldam o presente. Suas culturas são tão variadas quanto suas terras natais, e alguns já nascem com <b>magia no sangue</b>.',
          'Garen, Caitlyn, Ashe, Darius, Sivir', 'Qualquer um. Humanos com magia inata combinam com a fonte <b>Inato</b>; humanos comuns, com <b>Treinamento</b>.'],
        ['Plantífero', 'Seres de vida vegetal, geralmente nascidos da magia ou de espíritos ligados à natureza, e não de pais mortais. <b>Maokai</b> é um treant, um espírito da natureza das Ilhas Abençoadas distorcido pela Ruína. <b>Zyra</b> era a mente coletiva das plantas carnívoras dos Jardins de Zyr, que ganhou forma com a magia das Guerras Rúnicas. <b>Ivern</b> era um senhor da guerra humano transformado pelo Salgueiro-Deus num ser de madeira e folhas que conversa com os espíritos da terra.',
          'Maokai, Zyra, Ivern', 'Origem <b>Extraordinário</b> ou <b>Criado</b>; fonte <b>Natureza</b>; o poder <em>Plantas</em>; o <em>Princípio do Crescimento Selvagem</em>.'],
        ['Construto', 'Seres que foram feitos, e não nascidos: golens e criações animadas de vapor, relojoaria, pedra ou magia. Zaun construiu golens a vapor para limpar seus resíduos tóxicos, e um deles, <b>Blitzcrank</b>, ganhou consciência quando Viktor lhe instalou um núcleo hextec. <b>Orianna</b> é uma menina de relojoaria de Piltover; <b>Galio</b> é o colosso de petricita de Demacia, que só desperta na presença de magia forte. Noxus também tem os seus: <b>Briar</b> é uma arma viva criada pela Rosa Negra, uma sede de sangue presa num tronco de contenção que ela mesma aprendeu a abrir; <b>Sion</b> é um herói de guerra noxiano morto há séculos e reerguido por necromancia para voltar a lutar pelo império.',
          'Blitzcrank, Orianna, Galio, Briar, Sion', 'Origem <b>Criado</b>; fonte <b>Ser Artificial</b>; o Caminho <b>Robô/Ciborgue</b>.'],
        ['Meio-dragão', 'Seres raros com sangue de dragão, entre o mortal e o dragão. Os dragões de Runeterra ecoam os dragões celestiais, o primeiro dos quais foi Aurelion Sol, e alguns são elementais. <b>Shyvana</b> saiu de um ovo roubado da dragoa de fogo Yvva. Tem aparência humanoide, mas pode assumir sua forma de dragão completa, e luta pelo Príncipe Jarvan IV de Demacia.',
          'Shyvana', 'Origem <b>Extraordinário</b>; o Caminho <b>Metamorfo</b>; o poder <em>Fogo</em>.'],
        ['Troll', 'Um povo grandalhão, bruto e resistente das terras mais inóspitas de Runeterra, em especial os trolls do gelo do Freljord. Trolls são enormes e fortes, variam muito na aparência e se curam bem mais rápido que as outras raças mortais. Vivem em tribos, e muitos agora se reúnem em torno de <b>Trundle</b>, o Rei dos Trolls, que empunha um porrete de Gelo Verdadeiro.',
          'Trundle', 'O Caminho <b>Potência Física</b>; os poderes <em>Força</em> e <em>Vitalidade</em>; o <em>Princípio da Selvageria</em>.'],
        ['Vastaya', 'Um povo quimérico que mistura traços humanos e animais, descendente dos Vastayashai\'rei que absorveram o poder do Reino Espiritual durante a Guerra dos Titãs (veja a Linha do Tempo). Cada tribo lembra um animal diferente: raposas, aves, felinos, criaturas aquáticas e mais. A maioria dos vastaya tem magia inata e um vínculo com o Reino Espiritual. São mais comuns em Ionia, e muitas tribos desconfiam dos humanos.',
          'Ahri, Xayah, Rakan, Rengar, Nami, Neeko, Wukong', 'Origem <b>Extraordinário</b>; fontes <b>Natureza</b> ou <b>Interplanar</b>; o <em>Princípio da Fera</em>.'],
        ['Minotauro', 'Um povo chifrudo, orgulhoso e poderoso. Diferente dos vastaya, os minotauros não têm ancestrais mágicos: são uma raça própria. Por séculos, os clãs de minotauros guardaram as rotas comerciais terrestres para a antiga Zaun e evitaram as guerras de Valoran, até que Noxus exterminou o clã de <b>Alistar</b> e o obrigou a lutar como gladiador nas arenas.',
          'Alistar', 'Os Caminhos <b>Potência Física</b> ou <b>Blindado</b>; o poder <em>Força</em>; o <em>Princípio da Fúria</em> ou da <em>Liberdade</em>.'],
        ['Espírito', 'Seres do Reino Espiritual, de pequenos espíritos da natureza a semideuses. Alguns assumem forma física ou se prendem ao mundo material. Exemplos: <b>Janna</b>, espírito do vento; os <b>Kindred</b>, as faces gêmeas da morte; e demônios como Evelynn e Nocturne, nascidos das emoções e dos medos mortais. Em Ionia, onde o véu é fino, os espíritos moldam o dia a dia.',
          'Janna, Kindred, Evelynn, Nocturne, Fiddlesticks', 'Origem <b>Extraordinário</b>; fontes <b>Interplanar</b> ou <b>Sobrenatural</b>; o <em>Princípio do Imortal</em>.'],
        ['Yordle', 'Seres pequenos, peludos e mágicos, que no fundo são espíritos, vindos do reino atemporal de Bandópolis (veja Regiões). Os yordles são curiosos, caprichosos e muito mais perigosos do que parecem. Muitos vagam pelo mundo material como inventores, soldados, magos ou trapaceiros, e alguns são antiquíssimos: <b>Gnar</b> passou milênios congelado em Gelo Verdadeiro.',
          'Teemo, Tristana, Lulu, Veigar, Poppy, Heimerdinger, Gnar', 'Origem <b>Extraordinário</b>; fontes <b>Interplanar</b> ou <b>Gênio</b>; o <em>Princípio da Juventude</em> ou do <em>Caos</em>.']
      ].map(([n, d, ex, fit]) => `<div class="race"><h4>${n}</h4><p>${d}</p><p class="race-meta"><b>Exemplos:</b> ${ex}</p><p class="race-meta"><b>No criador, combina com:</b> ${fit}</p></div>`).join('')}` }
  ];
})();
