// pt-BR: textos da interface (inglês → português). O app usa T('texto em inglês').
(() => {
  'use strict';
  Object.assign(window.I18N.ui, {
    // painel de Lore
    'World lore': 'Lore do mundo', 'The world of the campaign': 'O mundo da campanha', 'Runeterra Lore': 'Lore de Runeterra',
    'Close lore': 'Fechar lore', 'Search the lore… (e.g. Void, Azir, petricite)': 'Buscar na lore… (ex.: Vazio, Azir, petricita)',
    'Search lore': 'Buscar na lore', 'Nothing in the lore matches your search.': 'Nada na lore corresponde à sua busca.',
    // resumo de regras
    'Rules cheat sheet': 'Resumo de regras', 'Quick reference': 'Referência rápida', 'Rules Cheat Sheet': 'Resumo de Regras',
    'Close cheat sheet': 'Fechar resumo', 'Search rules… (e.g. minion, twist, mod)': 'Buscar regras… (ex.: lacaio, reviravolta, mod)',
    'Search rules': 'Buscar regras', 'No rules match your search.': 'Nenhuma regra corresponde à sua busca.'
  });
})();
Object.assign(window.I18N.ui, {
 "Signature Quality": "Qualidade Marcante",
 "A custom quality that sums up your hero — your \"high concept\". Rather than a narrow skill, it covers many parts of who you are.": "Uma qualidade personalizada que resume seu herói, o seu \"conceito central\". Em vez de uma perícia específica, ela abrange várias facetas de quem você é.",
 "e.g. \"Hextech Prodigy of the Academy\", \"Last Kinkou of the Eastern Isles\", \"Bilgewater's Luckiest Liar\".": "ex.: \"Prodígio Hextec da Academia\", \"Último Kinkou das Ilhas Orientais\", \"O Mentiroso Mais Sortudo de Águas de Sentina\".",
 "Special": "Especial",
 "power": "poder",
 "quality": "qualidade",
 "powers": "poderes",
 "qualities": "qualidades",
 "In the Sentinels system every trait is a die — bigger is better (d4 → d6 → d8 → d10 → d12). ": "Cada característica é um dado, e quanto maior, melhor (d4 → d6 → d8 → d10 → d12). ",
 "Each roll uses a pool of <b>one power + one quality + your status die</b>.": "Cada rolagem usa uma reserva de <b>um poder + uma qualidade + seu dado de status</b>.",
 "As a power:": "Como poder:",
 "As a quality:": "Como qualidade:",
 "As a status die:": "Como dado de status:",
 "In Runeterra:": "Em Runeterra:",
 "Powers are what makes you exceptional — the first die in your pool.": "Poderes são o que te torna excepcional. Eles são o primeiro dado da sua reserva.",
 "Qualities are how you use your powers — the second die in your pool.": "Qualidades são o modo como você usa seus poderes. Elas são o segundo dado da sua reserva.",
 "any power": "qualquer poder",
 "any quality": "qualquer qualidade",
 "any {cat} power": "qualquer poder de {cat}",
 "any {cat} quality": "qualquer qualidade de {cat}",
 "Placeholder: when you take this ability you pick which {what} it uses. That choice is fixed on your sheet (it can only change through a Retcon or advancement).": "Espaço reservado: ao pegar esta habilidade, você escolhe qual {what} ela usa. A escolha fica fixa na sua ficha (só muda com uma Reviravolta do Destino ou uma evolução).",
 "power or quality": "poder ou qualidade",
 "Self Control power": "poder de Autocontrole",
 "Psychic power": "poder Psíquico",
 "Mental quality": "qualidade Mental",
 "Signature Vehicle": "Montaria Emblemática",
 "Signature Weaponry": "Arma Emblemática",
 "power from your Path": "poder do seu Caminho",
 "quality from your Path": "qualidade do seu Caminho",
 "Chosen for <b>[{what}]</b>": "Escolhido para <b>[{what}]</b>",
 "A choice you make when taking this ability (e.g. which element, which action). Fixed once chosen.": "Uma escolha feita ao pegar esta habilidade (ex.: qual elemento, qual ação). Fica fixa depois de escolhida.",
 "Decided each time you use the ability.": "Decidido toda vez que você usa a habilidade.",
 "Yellow abilities (choose {n}, each using a different power)": "Habilidades Amarelas (escolha {n}, cada uma usando um poder diferente)",
 "Yellow abilities (choose {n})": "Habilidades Amarelas (escolha {n})",
 "Yellow ability (choose {n})": "Habilidade Amarela (escolha {n})",
 "Green ability (choose 1)": "Habilidade Verde (escolha 1)",
 "Green ability (automatic)": "Habilidade Verde (automática)",
 "Green abilities (you gain both)": "Habilidades Verdes (você ganha as duas)",
 "Green abilities (choose {n})": "Habilidades Verdes (escolha {n})",
 "Using a different power or quality than your Green abilities.": "Usando um poder ou qualidade diferente das suas habilidades Verdes.",
 "Green forms (choose 2 form abilities, one per form)": "Formas Verdes (escolha 2 habilidades de forma, uma por forma)",
 "Each Green form gets a different ability usable only in that form. Record which powers/dice each form uses in your notes.": "Cada forma Verde recebe uma habilidade diferente, usável só naquela forma. Anote nas suas notas quais poderes/dados cada forma usa.",
 "Yellow form (choose 1)": "Forma Amarela (escolha 1)",
 "Your Yellow form may swap powers around and upgrade any two dice by one size.": "Sua forma Amarela pode trocar poderes de lugar e aumentar dois dados quaisquer em um tamanho.",
 "Red ability (automatic)": "Habilidade Vermelha (automática)",
 "Transformation ability (automatic)": "Habilidade de transformação (automática)",
 "Transformation ability (choose 1)": "Habilidade de transformação (escolha 1)",
 "Divided nature (choose 1)": "Natureza dividida (escolha 1)",
 "Green (automatic)": "Verde (automática)",
 "Yellow (automatic)": "Amarela (automática)",
 "Red (automatic)": "Vermelha (automática)",
 "Green mode (choose 1 besides your default mode)": "Modo Verde (escolha 1 além do seu modo padrão)",
 "Yellow modes (choose 2)": "Modos Amarelos (escolha 2)",
 "Red mode (choose 1)": "Modo Vermelho (escolha 1)",
 "— choose —": "Escolha…",
 "Pick {n} ({have}/{n} chosen).": "Escolha {n} ({have}/{n} escolhidas).",
 "Choose which power/quality “{ab}” uses.": "Escolha qual poder/qualidade “{ab}” usa.",
 "“{ab}” requires {trait}, which you don't have.": "“{ab}” exige {trait}, que você não tem.",
 "“{ab}” uses {trait}, which you no longer have.": "“{ab}” usa {trait}, que você não tem mais.",
 "Choose the quality for “{ab}”.": "Escolha a qualidade de “{ab}”.",
 "Choose [{what}] for “{ab}”.": "Escolha [{what}] para “{ab}”.",
 "Each ability must use a different power/quality.": "Cada habilidade precisa usar um poder/qualidade diferente.",
 "Use at least {n} different powers across these abilities.": "Use pelo menos {n} poderes diferentes entre estas habilidades.",
 "Use at least {n} different powers/qualities across these abilities.": "Use pelo menos {n} poderes/qualidades diferentes entre estas habilidades.",
 "These abilities must include: {list}.": "Estas habilidades precisam incluir: {list}.",
 "one using {what}": "uma usando {what}",
 ", and ": " e ",
 "your Signature Weapon": "sua Arma Emblemática",
 "one of your qualities": "uma das suas qualidades",
 "one of your powers": "um dos seus poderes",
 "Melee Combat (Close Combat)": "Combate Corpo a Corpo",
 "Flight or your Signature Mount/Vehicle": "Voo ou sua Montaria Emblemática",
 "“{ab}” must use a different power or quality than your Green abilities ({trait} is already used there).": "“{ab}” precisa usar um poder ou qualidade diferente das suas habilidades Verdes ({trait} já é usado lá).",
 "Assign your {die} (freed die).": "Atribua seu {die} (dado liberado).",
 "Assign your {die}.": "Atribua seu {die}.",
 "Choose {p}.": "Escolha {p}.",
 "Choose {p}": "Escolha {p}",
 "Choose your element for this principle.": "Escolha seu elemento para este princípio.",
 "Your two principles must be different.": "Seus dois princípios precisam ser diferentes.",
 "Esoteric": "Esotérico",
 "Expertise": "Especialidade",
 "Ideals": "Ideais",
 "Identity": "Identidade",
 "Responsibility": "Responsabilidade",
 "Tick the boxes to choose, then pick which power or quality each ability uses from its drop-down.": "Marque as caixas para escolher e depois selecione, no menu de cada habilidade, qual poder ou qualidade ela usa.",
 "Roll the dice.": "Role os dados.",
 "Press <b>Roll</b>. The highlighted entries are the ones you can pick.": "Aperte <b>Rolar</b>. As opções destacadas são as que você pode escolher.",
 "Choose your homeland": "Escolha sua terra natal",
 "Choose a homeland.": "Escolha uma terra natal.",
 "Click the land your champion comes from. Hover a card to preview it.": "Clique na <b>terra</b> de onde seu campeão vem. Passe o mouse sobre um cartão para ver detalhes.",
 "Roll for your Origin": "Role sua Origem",
 "Choose your Origin": "Escolha sua Origem",
 "Choose an Origin.": "Escolha uma Origem.",
 "Click one of the Origins highlighted by your roll. Hover the <b>i</b> to see what it gives you.": "Clique em uma das Origens <b>destacadas</b> pela sua rolagem. Passe o mouse num cartão para ver o que ela dá.",
 "Click one of the Origins. Hover the <b>i</b> to see what it gives you.": "Clique em uma <b>Origem</b>. Passe o mouse num cartão para ver o que ela dá.",
 "One die must go to {trait}.": "Um dado precisa ir para {trait}.",
 "Assign your quality dice": "Atribua seus dados de qualidade",
 "Click a die, then choose the quality it becomes. Bigger dice mean you are better at it.": "Clique em um <b>dado</b> e escolha a <b>qualidade</b> que ele vira. Quanto <b>maior o dado</b>, melhor você é naquilo.",
 "Choose your first principle": "Escolha seu primeiro princípio",
 "Principles are what your champion believes in. Click one — hover to read it in full.": "<b>Princípios</b> são aquilo em que seu campeão <b>acredita</b>. Clique em um para escolher ou passe o mouse para ler o texto completo.",
 "Roll your Origin dice": "Role os dados da sua Origem",
 "Choose your Source of Power": "Escolha sua Fonte de Poder",
 "Choose a Source of Power.": "Escolha uma Fonte de Poder.",
 "Click where your champion's power comes from. Hover the <b>i</b> for details.": "Clique no que deu <b>poder</b> ao seu campeão. Passe o mouse num cartão para ver o que ela dá.",
 "Assign your power dice": "Atribua seus dados de poder",
 "Click a die, then choose the power it becomes.": "Clique em um <b>dado</b> e escolha o <b>poder</b> que ele vira.",
 "Make your choice.": "Faça sua escolha.",
 "Choose the Void-touched upgrade.": "Escolha o aprimoramento tocado pelo Vazio.",
 "Choose which power to downgrade and which to upgrade.": "Escolha qual poder diminuir e qual aumentar.",
 "Special bonus": "Bônus especial",
 "Choose your abilities": "Escolha suas habilidades",
 "Roll your Source dice": "Role os dados da sua Fonte",
 "Choose your Path": "Escolha seu Caminho",
 "Choose a Path.": "Escolha um Caminho.",
 "Click how your champion fights. <b>Two Souls</b> and <b>Stance Master</b> are advanced options.": "Clique em como seu campeão <b>luta</b>. <b>Duas Almas</b> e <b>Mestre das Posturas</b> são opções avançadas.",
 "Roll for your base Path": "Role seu Caminho base",
 "Choose your base Path": "Escolha seu Caminho base",
 "Choose the base Path.": "Escolha o Caminho base.",
 "Press <b>Roll</b> for your base Path.": "Aperte <b>Rolar</b> para seu Caminho base.",
 "Your second Path provides your dice and abilities.": "Seu segundo Caminho fornece seus dados e habilidades.",
 "Your base Path decides how your dice are assigned.": "Seu Caminho base decide como seus dados são atribuídos.",
 "You need {what}.": "Você precisa ter {what}.",
 "Only one of the remaining dice may go to a power (the rest go to qualities).": "Só um dos dados restantes pode ir para um poder (o resto vai para qualidades).",
 "One of the remaining dice must go to a power.": "Um dos dados restantes precisa ir para um poder.",
 "At least one die must go to a power.": "Pelo menos um dado precisa ir para um poder.",
 "Add a d6 power (Stance Masters need four powers).": "Adicione um poder d6 (Mestres das Posturas precisam de quatro poderes).",
 "Assign your dice": "Atribua seus dados",
 "Click a die, then choose the power or quality it becomes. Read the rules above the dice — some must go to specific things.": "Clique em um <b>dado</b> e escolha o <b>poder ou qualidade</b> que ele vira. Leia as <b>regras acima dos dados</b>, porque alguns precisam ir para lugares específicos.",
 "Choose your method of transformation": "Escolha seu método de transformação",
 "Choose a method.": "Escolha um método.",
 "How does your champion switch between their two forms?": "Como seu campeão alterna entre as duas formas?",
 "Choose the quality that sets your number of minion forms.": "Escolha a qualidade que define seu número de formas de lacaio.",
 "Choose {n} minion forms ({have} chosen).": "Escolha {n} formas de lacaio ({have} escolhidas).",
 "Choose your minion forms": "Escolha suas formas de lacaio",
 "Pick the quality first, then tick as many forms as it allows.": "Escolha a qualidade primeiro e depois marque quantas formas ela permitir.",
 "Notes on your modes (optional)": "Notas sobre seus modos (opcional)",
 "Notes on your forms (optional)": "Notas sobre suas formas (opcional)",
 "Optional — jot down which powers each form or mode uses.": "Se quiser, anote quais poderes cada forma ou modo usa.",
 "Choose your second principle": "Escolha seu segundo princípio",
 "Click a principle — it must be different from your first one.": "Clique em um princípio <b>diferente do primeiro</b>.",
 "Roll for your Temperament": "Role seu Temperamento",
 "Choose your Temperament": "Escolha seu Temperamento",
 "Choose a Temperament.": "Escolha um Temperamento.",
 "Click how your champion behaves under pressure. The three dice are your Green / Yellow / Red status.": "Clique em um <b>Temperamento</b>. Passe o mouse num cartão para ver a habilidade de <b>Nocaute</b>.",
 "Name your Signature Quality": "Dê nome à sua Qualidade Marcante",
 "Type a name for your Signature Quality.": "Digite um nome para sua Qualidade Marcante.",
 "Type a short phrase that sums up your champion, like <em>Last Kinkou of the Eastern Isles</em>.": "Digite uma <b>frase curta</b> que resuma seu campeão, como <em>Último Kinkou das Ilhas Orientais</em>.",
 "Set up your Out ability": "Configure sua habilidade de Nocaute",
 "Choose which trait your Out ability uses.": "Escolha qual característica sua habilidade de Nocaute usa.",
 "Pick the power or quality used when you're knocked out.": "Escolha o poder ou qualidade usado quando você é nocauteado.",
 "Reckless upgrade": "Aprimoramento impulsivo",
 "Choose a power or quality to upgrade.": "Escolha um poder ou qualidade para aumentar.",
 "Pick one trait to raise by one die size.": "Escolha uma característica para <b>subir um tamanho de dado</b>.",
 "Pick {n} Ultimates ({have}/{n} chosen).": "Escolha {n} Supremas ({have}/{n} escolhidas).",
 "Choose which trait “{ab}” uses.": "Escolha qual característica “{ab}” usa.",
 "Choose {n} Ultimates": "Escolha {n} Supremas",
 "Only categories marked <b>eligible</b> can be picked — they match powers and qualities you have. Tick {n} abilities, then choose the trait each one uses.": "Marque <b>{n}</b> habilidades e escolha o <b>poder ou qualidade</b> que cada uma usa.",
 "Choose one Twist of Fate": "Escolha uma Reviravolta do Destino",
 "Choose one option.": "Escolha uma opção.",
 "Pick one small tweak to your champion.": "Clique em <b>uma</b> opção. Passe o mouse para ver o que ela muda.",
 "Pick two different traits to swap.": "Escolha duas características diferentes para trocar.",
 "Pick the new d6 power or quality.": "Escolha o novo poder ou qualidade d6.",
 "Pick which principle to change and its replacement.": "Escolha qual princípio trocar e o substituto.",
 "Your Red status die is already d12 — pick another option.": "Seu dado de status Vermelho já é d12. Escolha outra opção.",
 "Go back to Ultimates and pick your third Red ability.": "Volte às Supremas e escolha sua terceira habilidade Vermelha.",
 "Set it up": "Detalhes da escolha",
 "Complete the choice for your Twist of Fate.": "Complete a escolha da sua Reviravolta do Destino.",
 "Review your Health": "Revise sua Vida",
 "Pick the trait that adds to your Health and whether to roll.": "Escolha a característica que soma à sua Vida e se vai rolar ou não.",
 "Name your champion": "Dê nome ao seu campeão",
 "Name your champion (optional)": "Dê nome ao seu campeão (opcional)",
 "Type your champion's name.": "Digite o nome do seu campeão.",
 "Type a hero name — you can fill in the rest below at your own pace.": "Digite um nome de herói. O resto você preenche abaixo, no seu ritmo.",
 "Describe them (optional)": "Descreva-o (opcional)",
 "Optional details for your hero sheet.": "Detalhes opcionais para sua ficha de herói.",
 "Name your abilities (optional)": "Dê nome às suas habilidades (opcional)",
 "Optional — give your abilities Runeterran names.": "Se quiser, dê nomes runeterranos às suas habilidades.",
 "Name your gear & gifts (optional)": "Dê nome ao seu equipamento e dons (opcional)",
 "Optional — rename your Signature Weapon, powers and so on.": "Se quiser, renomeie sua Arma Emblemática, seus poderes e afins.",
 "Constructed method: pick whichever entry fits your concept. The dice {dice} still matter for what you assign.": "Método Construído: escolha a opção que combina com seu conceito. Os dados {dice} continuam valendo para o que você atribuir.",
 "You may choose:": "Você pode escolher:",
 "(any single die, or the sum of any two)": "(qualquer dado sozinho, ou a soma de dois)",
 "<h5>Guided method</h5>Roll the listed dice. You may pick the table entry equal to any single die <b>or</b> the sum of any two dice. If nothing fits your idea, you may re-roll once per step. Only the die <b>sizes</b> carry on to your powers/qualities — not the numbers.": "<h5>Método Guiado</h5>Role os dados indicados. Você pode escolher a opção da tabela igual a qualquer dado sozinho <b>ou</b> à soma de dois dados. Se nada combinar com sua ideia, pode rolar de novo uma vez por passo. Seus poderes e qualidades recebem só o <b>tamanho</b> dos dados, não os números rolados.",
 "Roll": "Rolar",
 "Re-roll (once)": "Rolar de novo (uma vez)",
 "Re-roll used.": "Nova rolagem usada.",
 "Suits a champion from {place}": "Combina com um campeão de {place}",
 "on your {die}": "no seu {die}",
 "have {die}": "já tem {die}",
 "Already had {trait} at {from}: it becomes {to} and the other die is freed below.": "Você já tinha {trait} em {from}: vira {to} e o outro dado fica livre abaixo.",
 "Freed die from {trait} (“I've already got that” rule).": "Dado liberado de {trait} (regra “Eu já tenho isso”).",
 "Bind this {die} to a trait": "Vincule este {die} a uma característica",
 "<h5>Assigning dice</h5>Only the die <b>size</b> matters. Each die becomes the rating of one power or quality. Powers and qualities you already have cannot be chosen again.": "<h5>Atribuindo dados</h5>Só o <b>tamanho</b> do dado importa. Cada dado vira a graduação de um poder ou qualidade. Poderes e qualidades que você já tem não podem ser escolhidos de novo.",
 "You already had {trait}: bind this {die} to something else.": "Você já tinha {trait}: vincule este {die} a outra coisa.",
 "Suits {who}": "Combina com {who}",
 "Nothing to choose here: this bonus shows up in the Path chapter.": "Nada para escolher aqui: este bônus aparece no capítulo Caminho.",
 "<b>New to the game?</b> Pick <b>Constructed</b>. You can switch at any time; progress is kept in this browser.": "<b>Primeira vez?</b> Escolha <b>Construído</b>. Dá para trocar a qualquer momento, e o progresso fica salvo neste navegador.",
 "Of the other dice, <b>exactly one</b> goes to powers.": "Dos outros dados, <b>exatamente um</b> vai para poderes.",
 "Of the other dice, <b>any number</b> (even none) go to powers.": "Dos outros dados, <b>qualquer quantidade</b> (até nenhum) vai para poderes.",
 "Of the other dice, <b>one or more</b> go to powers.": "Dos outros dados, <b>um ou mais</b> vão para poderes.",
 "<b>Exactly one die</b> goes to powers.": "<b>Exatamente um dado</b> vai para poderes.",
 "<b>Any number of dice</b> (even none) go to powers.": "<b>Qualquer quantidade de dados</b> (até nenhum) vai para poderes.",
 "<b>One or more dice</b> go to powers.": "<b>Um ou mais dados</b> vão para poderes.",
 "Every die left over goes to qualities.": "Todo dado que sobrar vai para qualidades.",
 "Skip": "Pular",
 "Unknown ability": "Habilidade desconhecida",
 "{cat} power": "poder de {cat}",
 "{cat} quality": "qualidade de {cat}",
 "Uses {what}": "Usa {what}",
 "You have no eligible trait yet.": "Você ainda não tem uma característica válida.",
 " — which you don't have!": ", que você não tem!",
 "Quality": "Qualidade",
 "e.g. Attack and Overcome": "ex.: Atacar e Superar",
 "Type: {t}": "Tipo: {t}",
 "Green ability": "Habilidade Verde",
 "Yellow ability": "Habilidade Amarela",
 "Red ability": "Habilidade Vermelha",
 "Out ability": "Habilidade de Nocaute",
 "Select": "Selecionar",
 "Toggle": "Alternar",
 "green": "verde",
 "yellow": "amarela",
 "red": "vermelha",
 "out": "nocaute",
 "Mode:": "Modo:",
 "chosen": "escolhidas",
 "During roleplaying:": "Durante a interpretação:",
 "Minor twist:": "Reviravolta menor:",
 "Major twist:": "Reviravolta maior:",
 "Green ability ({t}):": "Habilidade Verde ({t}):",
 "Your element": "Seu elemento",
 "The twist questions are prompts the GM may ask when a twist happens. Record the questions, not answers.": "As perguntas de reviravolta são deixas que o Mestre pode usar quando uma reviravolta acontece. Anote as perguntas, não as respostas.",
 "{cat} principles": "Princípios de {cat}",
 "Each principle gives roleplaying guidance, a Minor and Major twist question, and a Green ability that earns hero points for the whole team.": "Cada princípio traz uma orientação de interpretação, uma pergunta de reviravolta menor e uma maior, e uma habilidade Verde que rende pontos de herói para o grupo todo.",
 "Chosen:": "Escolhido:",
 "Change": "Trocar",
 "Pick a different principle below, or": "Escolha outro princípio abaixo, ou",
 "keep the current choice": "mantenha a escolha atual",
 "Boost": "Fortalecer",
 "Hinder": "Atrapalhar",
 "physical": "físico",
 "energy": "energia",
 "Homeland": "Terra Natal",
 "The land that shaped you": "A terra que te moldou",
 "Origin": "Origem",
 "Where you came from": "De onde você veio",
 "Source of Power": "Fonte de Poder",
 "What changed you": "O que te transformou",
 "Path": "Caminho",
 "How you fight": "Como você luta",
 "Temperament": "Temperamento",
 "How you face pressure": "Como você encara a pressão",
 "Ultimates": "Supremas",
 "What you unleash when all is lost": "O que você libera quando tudo parece perdido",
 "Twist of Fate": "Reviravolta do Destino",
 "One last tweak": "Um último ajuste",
 "Health": "Vida",
 "How much you can endure": "O quanto você aguenta",
 "Legend": "Lenda",
 "Your name and your sheet": "Seu nome e sua ficha",
 "A codex for the Sentinels roleplaying system": "Um códice para forjar campeões",
 "Forge a Champion <span>of Runeterra</span>": "Forje um Campeão <span>de Runeterra</span>",
 "Nine chapters take you from a nameless wanderer to a champion ready for the table — where you were born, what gave you power, how you fight, and what you will become when everything is on the line.": "Dez capítulos levam você de um andarilho sem nome a um campeão pronto para a mesa. Aqui você decide de que povo é, onde nasceu, o que te deu poder, como luta e no que se torna quando tudo está em jogo.",
 "Every Runeterran name hides the rule behind it:": "Todo nome runeterrano esconde a regra por trás dele:",
 "<h5>Hover and learn</h5>Anything underlined like this explains itself. Runeterra names show the Sentinels RPG rule they stand for.": "<h5>Passe o mouse e aprenda</h5>Tudo que estiver sublinhado assim se explica sozinho. Cada nome mostra a regra que ele representa.",
 "hover anything underlined": "passe o mouse no que estiver sublinhado",
 "New to the world? Read the": "Novo no mundo? Leia a",
 "lore": "lore",
 "New to the rules? Open the": "Novo nas regras? Abra o",
 "cheat sheet": "resumo de regras",
 "Choose how fate is decided": "Escolha como o destino será decidido",
 "Creation method": "Método de criação",
 "Guided": "Guiado",
 "Roll the dice at every chapter and choose among the paths they open. Let the Runes decide.": "Role os dados a cada capítulo e escolha entre os caminhos que eles abrem. Deixe as Runas decidirem.",
 "Constructed": "Construído",
 "Pick freely to build the champion you already imagine. Same dice, your choice.": "Escolha livremente para montar o campeão que você já imagina. Os mesmos dados, a sua escolha.",
 "You can switch at any time. Progress is kept in this browser.": "Você pode trocar a qualquer momento. O progresso fica salvo neste navegador.",
 "Chapter I": "Capítulo I",
 "Begin the chronicle": "Começar a crônica",
 "The Chapters": "Os Capítulos",
 "How a roll works": "Como funciona uma rolagem",
 "Every action rolls <b>three dice</b> —": "Toda ação rola <b>três dados</b>:",
 "<h5>Powers</h5>Exceptional traits — magic, Hextech, Ascended strength. Rated d6 (above average) to d12 (godlike).": "<h5>Poderes</h5>Características excepcionais, como magia, hextec ou a força dos Ascendentes. Vão de d6 (acima da média) a d12 (divino).",
 "a power": "um poder",
 "<h5>Qualities</h5>Learned skills and knowledge. Rated d6 (solid competency) to d12 (world class).": "<h5>Qualidades</h5>Habilidades e conhecimentos aprendidos. Vão de d6 (competência sólida) a d12 (nível mundial).",
 "a quality": "uma qualidade",
 "and your": "e seu",
 "status": "status",
 "sorted into": "que são ordenados em",
 "Min die, Mid die and Max die": "dado Mín, dado Médio e dado Máx",
 "As {health} falls you pass from the {g} to the {y} and {r}, unlocking stronger abilities.": "Conforme a {health} cai, você passa da {g} para a {y} e a {r}, liberando habilidades mais fortes.",
 "Green zone": "Zona Verde",
 "Yellow zone": "Zona Amarela",
 "Red zone": "Zona Vermelha",
 "Choose": "Escolher",
 "Close": "Fechar",
 "Filter {n} options…": "Filtrar {n} opções…",
 "Filter options": "Filtrar opções",
 "Options": "Opções",
 "Unbind this die": "Desvincular este dado",
 "You are here": "Você está aqui",
 "Done": "Feito",
 "Sealed — finish the step above": "Selado até você terminar o passo acima",
 "Still to do": "Ainda falta",
 "Now": "Agora",
 "Show me": "Mostrar",
 "This chapter is complete.": "Este capítulo está completo.",
 "Two forms, a civilian one and a heroic one, and a way to switch between them.": "Duas formas, uma civil e uma heroica, e um jeito de trocar entre elas.",
 "Switchable modes instead of fixed abilities.": "Modos que você alterna, em vez de habilidades fixas.",
 "Health roll": "Vida: pegar 4 ou rolar",
 "Not available after rolling.": "Indisponível depois de rolar.",
 "Safe: always 4.": "Seguro: sempre 4.",
 "Rolled {n}": "Tirou {n}",
 "Final: after rolling you cannot go back to 4.": "Definitivo: depois de rolar, não dá para voltar ao 4.",
 "You may re-roll once.": "Você pode rolar de novo uma vez.",
 "Re-roll already used.": "Nova rolagem já usada.",
 "Click to re-roll (once).": "Clique para rolar de novo (uma vez).",
 "Press Confirm to keep this name.": "Clique em Confirmar para ficar com este nome.",
 "Type your Signature Quality": "Digite sua Qualidade Marcante",
 "Confirm": "Confirmar",
 "{n} chosen": "{n} escolhida(s)",
 "{n} abilities": "{n} habilidades",
 "Open a category to see its abilities.": "Abra uma categoria para ver as habilidades dela.",
 "Which power or quality does this {die} become?": "Este {die} vira qual poder ou qualidade?",
 "Which power does this {die} become?": "Este {die} vira qual poder?",
 "Which quality does this {die} become?": "Este {die} vira qual qualidade?",
 "becomes": "vira",
 "Powers: what makes you extraordinary.": "Poderes: o que te torna extraordinário.",
 "Qualities: what you know how to do.": "Qualidades: o que você sabe fazer.",
 "Suggestion": "Sugestão",
 "Only a suggestion: you can pick any option.": "É só uma sugestão: você pode escolher qualquer opção.",
 "<b>Suggestion</b> for your People and Homeland. Only a suggestion: you can pick any option.": "<b>Sugestão</b> pelo seu Povo e Terra Natal. É só uma sugestão: você pode escolher qualquer opção.",
 "Continue": "Continuar",
 "Open this part again": "Abrir esta parte de novo",
 "Health {n}": "Vida {n}",
 "Continue to <b>{next}</b> when you are ready.": "Siga para <b>{next}</b> quando estiver pronto.",
 "Pick a different option below, or": "Escolha outra opção abaixo.",
 "Champions": "Campeões",
 "any {cat}": "qualquer {cat}",
 "Qualities:": "Qualidades:",
 "assign {dice} to {n} of:": "atribua {dice} a {n} entre:",
 "Principle:": "Princípio:",
 "Power Source dice:": "Dados de Fonte de Poder:",
 "Champions:": "Campeões:",
 "Powers:": "Poderes:",
 "Required:": "Obrigatório:",
 "one die to {trait}": "um dado em {trait}",
 "Yellow (choose 2):": "Amarelas (escolha 2):",
 "Green (choose 1):": "Verde (escolha 1):",
 "Instead of Green:": "No lugar da Verde:",
 "Path dice:": "Dados de Caminho:",
 "Pick a second Path as your base; you gain a civilian and a heroic form plus a transformation method. Principle: Responsibility.": "Escolha um segundo Caminho como base; você ganha uma forma civil e uma heroica, além de um método de transformação. Princípio: Responsabilidade.",
 "Pick a base Path for your dice, but instead of its abilities you gain switchable modes (Green, Yellow and Red). Principle: from the base Path.": "Escolha um Caminho base para seus dados, mas no lugar das habilidades dele você ganha modos alternáveis (Verde, Amarelo e Vermelho). Princípio: o do Caminho base.",
 "Green:": "Verde:",
 "Yellow:": "Amarela:",
 "one of the Green list": "uma da lista Verde",
 "Chapter": "Capítulo",
 "of IX": "de IX",
 "Read the full lore of {place}": "Leia a lore completa de {place}",
 "Fitting Origins": "Origens que combinam",
 "Fitting Sources": "Fontes que combinam",
 "Fitting Principles": "Princípios que combinam",
 "No rules effect. Options marked {mark} <b>{place}</b> in later steps are only suggestions.": "Sem efeito nas regras. As opções marcadas com {mark} <b>{place}</b> nos próximos passos são só sugestões.",
 "New to Runeterra? Read the <a href=\"#\" data-act=\"lore\" data-section=\"lore-planet\">world lore</a> first.": "Novo em Runeterra? Leia antes a <a href=\"#\" data-act=\"lore\" data-section=\"lore-planet\">lore do mundo</a>.",
 "Roll 2d10 for your Origin": "Role 2d10 para sua Origem",
 "Highlighted cards match your roll.": "Os cards destacados correspondem à sua rolagem.",
 "Details": "Detalhes",
 "Assign {dice} to {n} of: {opts}.": "Atribua {dice} a {n} entre: {opts}.",
 "One die <b>must</b> go to {trait}.": "Um dado <b>precisa</b> ir para {trait}.",
 "Assign each die to a quality:": "Atribua cada dado a uma qualidade:",
 "Next step: your Source of Power, rolled with {dice}.": "Próximo passo: sua Fonte de Poder, rolada com {dice}.",
 "Raise which d6 to d8?": "Qual d6 sobe para d8?",
 "You have no d6 powers, so instead add a new power from the list at d6.": "Você não tem poderes d6, então adicione um poder novo da lista em d6.",
 "Bind this d6 to a new power": "Vincule este d6 a um poder novo",
 "Shrink one power by a size": "Diminua um poder em um tamanho",
 "Grow one power by a size": "Aumente um poder em um tamanho",
 "Choose your Origin first — it gives the dice you roll here.": "Escolha sua Origem primeiro, pois é ela que dá os dados que você rola aqui.",
 "Assign one of the dice from your Origin ({dice}) to {trait} — this one is required. Every other die goes to a power: {opts}.": "Atribua um dos dados da sua Origem ({dice}) a {trait}. Este é obrigatório. Todos os outros dados vão para um poder: {opts}.",
 "Every die from your Origin ({dice}) goes to a power: {opts}.": "Cada dado da sua Origem ({dice}) vai para um poder: {opts}.",
 "Signature Weapon / Mount can be renamed in the last step (e.g. “Hextech Rifle”, “Valor”).": "A Arma / Montaria Emblemática pode ser renomeada no último passo (ex.: “Rifle Hextec”, “Valor”).",
 "Assign each die to a power:": "Atribua cada dado a um poder:",
 "Choose your Source of Power first — it gives the dice you roll here.": "Escolha sua Fonte de Poder primeiro, pois é ela que dá os dados que você rola aqui.",
 "advanced": "avançado",
 "Your full Path becomes “{name}”.": "Seu Caminho completo vira “{name}”.",
 "You follow this Path's dice rules, but gain modes instead of its abilities.": "Você segue as regras de dados deste Caminho, mas ganha modos no lugar das habilidades dele.",
 "Of the other dice, <b>exactly one</b> goes to powers: {opts}.": "Dos outros dados, <b>exatamente um</b> vai para poderes: {opts}.",
 "<b>Exactly one die</b> goes to powers: {opts}.": "<b>Exatamente um dado</b> vai para poderes: {opts}.",
 "Of the other dice, <b>any number</b> (even none) go to powers: {opts}.": "Dos outros dados, <b>quantos quiser</b> (até nenhum) vão para poderes: {opts}.",
 "<b>Any number of dice</b> (even none) go to powers: {opts}.": "<b>Quantos dados quiser</b> (até nenhum) vão para poderes: {opts}.",
 "Of the other dice, <b>one or more</b> go to powers: {opts}.": "Dos outros dados, <b>um ou mais</b> vão para poderes: {opts}.",
 "<b>One or more dice</b> go to powers: {opts}.": "<b>Um ou mais dados</b> vão para poderes: {opts}.",
 "Assign the dice from your Source ({dice}).": "Atribua os dados da sua Fonte ({dice}).",
 "You <b>must</b> end this step with <b>{what}</b> — ones you already have count, so put dice there only until you have two.": "Você <b>precisa</b> terminar este passo com <b>{what}</b>. Os que você já tem contam, então só coloque dados lá até completar dois.",
 "First, one die <b>must</b> go to <b>{what}</b>. If you already have it, you may skip this and use the die below instead.": "Primeiro, um dado <b>precisa</b> ir para <b>{what}</b>. Se você já tiver, pode pular isso e usar o dado abaixo.",
 "Every die left over goes to qualities: {opts}.": "Todo dado que sobrar vai para qualidades: {opts}.",
 "It is fine to put every die into powers and take no quality here.": "Tudo bem colocar todos os dados em poderes e não pegar nenhuma qualidade aqui.",
 "Assign each die:": "Atribua cada dado:",
 "From your <b>{src}</b> source: one extra quality from this Path's list at {die}.": "Da sua fonte <b>{src}</b>: uma qualidade extra da lista deste Caminho em {die}.",
 "Training bonus quality:": "Qualidade bônus do Treinamento:",
 "Stance Masters need at least four powers — add {n} {die} power(s):": "Mestres das Posturas precisam de pelo menos quatro poderes. Adicione {n} poder(es) {die}:",
 "on another d6": "em outro d6",
 "Bind this d6 to any power": "Vincule este d6 a qualquer poder",
 "When determining Health you may use a {cat} power instead of an Athletic power or Mental quality.": "Ao calcular a Vida, você pode usar um poder de {cat} no lugar de um poder Atlético ou uma qualidade Mental.",
 " or ": " ou ",
 " and ": " e ",
 "As a {path}, the Red abilities {list} are added to your options in the Ultimates step.": "Como {path}, as habilidades Vermelhas {list} entram nas suas opções no passo das Supremas.",
 "Record which powers/dice each mode uses (this goes on your auxiliary sheet).": "Anote quais poderes/dados cada modo usa (isso vai na sua ficha auxiliar).",
 "Record which powers/dice each form uses (this goes on your auxiliary sheet).": "Anote quais poderes/dados cada forma usa (isso vai na sua ficha auxiliar).",
 "Next step: your Temperament, rolled with {dice}.": "Próximo passo: seu Temperamento, rolado com {dice}.",
 "<h5>Minion forms</h5>When you create a minion you may discard one bonus you have access to in order to add a form with that bonus value or higher. The number of forms you know equals the maximum value of a related quality.": "<h5>Formas de lacaio</h5>Ao criar um lacaio, você pode descartar um bônus a que tem acesso para adicionar uma forma com aquele valor de bônus ou mais. O número de formas que você conhece é igual ao valor máximo de uma qualidade relacionada.",
 "You know as many minion forms as the maximum value of a related quality.": "Você conhece tantas formas de lacaio quanto o valor máximo de uma qualidade relacionada.",
 "Related quality": "Qualidade relacionada",
 "You need {list}.": "Você precisa de {list}.",
 "Bonus needed to apply this form": "Bônus necessário para aplicar esta forma",
 "{b} or higher": "{b} ou mais",
 "Choose your Path first.": "Escolha seu Caminho primeiro.",
 "Roll 2d10 for your Temperament": "Role 2d10 para seu Temperamento",
 "<h5>Status dice</h5>The third die of every roll. Which one you use depends on your current Health zone.": "<h5>Dados de status</h5>O terceiro dado de toda rolagem. Qual você usa depende da sua zona de Vida atual.",
 "Green": "Verde",
 "Yellow": "Amarelo",
 "Red": "Vermelho",
 "When determining Health you may use <b>any</b> power or quality.": "Ao calcular a Vida, você pode usar <b>qualquer</b> poder ou qualidade.",
 "Status:": "Status:",
 "Out:": "Nocaute:",
 "A {die} quality that sums up your champion — your “high concept”. Examples: <em>Hextech Prodigy of the Academy</em>, <em>Last Kinkou of the Eastern Isles</em>, <em>Bilgewater's Luckiest Liar</em>.": "Uma qualidade {die} que resume seu campeão, o seu “conceito central”. Exemplos: <em>Prodígio Hextec da Academia</em>, <em>Último Kinkou das Ilhas Orientais</em>, <em>O Mentiroso Mais Sortudo de Águas de Sentina</em>.",
 "Type your Signature Quality, then press Enter": "Ex.: Última Lâmina da Guarda de Ferro",
 "Used when your champion is knocked out.": "Usada quando seu campeão é nocauteado.",
 "Uses": "Usa",
 "Upgrade one of your power or quality dice by one step (max {die}).": "Aumente um dos seus dados de poder ou qualidade em um tamanho (máx. {die}).",
 "Grow one die by a size": "Aumente um dado em um tamanho",
 "Choose your Temperament first.": "Escolha seu Temperamento primeiro.",
 "eligible": "elegível",
 "You have:": "Você tem:",
 "+1 from Twist of Fate": "+1 da Reviravolta do Destino",
 "You need a power or quality of these categories rated d6 or higher to take their Red abilities.": "Você precisa de um poder ou qualidade dessas categorias em d6 ou mais para pegar as habilidades Vermelhas delas.",
 "Not available to you (you have no traits in these categories):": "Indisponíveis para você (você não tem características nestas categorias):",
 "{cat} powers": "poderes de {cat}",
 "{cat} qualities": "qualidades de {cat}",
 "First trait to swap": "Primeira característica a trocar",
 "Swap its die with…": "Trocar o dado dela com…",
 "Bind this d6 to any power or quality": "Vincule este d6 a qualquer poder ou qualidade",
 "Replace": "Substituir",
 "Origin principle": "Princípio da Origem",
 "Path principle": "Princípio do Caminho",
 "With (any category)": "Por (qualquer categoria)",
 "Go back to any ability (Source, Path or Ultimates) and change which power or quality it uses. Everything stays editable — this option simply makes it “official”.": "Volte a qualquer habilidade (Fonte, Caminho ou Supremas) e troque o poder ou qualidade que ela usa. Tudo continua editável, e esta opção só torna a troca “oficial”.",
 "Red status die:": "Dado de status Vermelho:",
 "Go back to <a href=\"#\" data-act=\"go\" data-step=\"red\">Ultimates</a> and pick a third Red ability ({n}/3 chosen).": "Volte às <a href=\"#\" data-act=\"go\" data-step=\"red\">Supremas</a> e escolha uma terceira habilidade Vermelha ({n}/3 escolhidas).",
 "Choose your Temperament first (your Red status die is part of Health).": "Escolha seu Temperamento primeiro (seu dado de status Vermelho faz parte da Vida).",
 "Trait added to Health (highest by default)": "Característica somada à Vida (a maior, por padrão)",
 "none — use d4": "nenhuma (use d4)",
 "Take 4": "Pegar 4",
 "Rolled {n} — roll again": "Tirou {n}. Rolar de novo",
 "Roll d8": "Rolar d8",
 "Decide whether to roll <em>before</em> rolling.": "Decida se vai rolar <em>antes</em> de rolar.",
 "Rolled {n}. Re-roll already used.": "Tirou {n}. A nova rolagem já foi usada.",
 "Rolled {n}. Re-roll once": "Tirou {n}. Rolar de novo (1 vez)",
 "Decide whether to roll <em>before</em> rolling. You may re-roll once, and then the result stays.": "Decida se vai rolar <em>antes</em> de rolar. Você pode rolar de novo uma vez, e então o resultado fica.",
 "Base": "Base",
 "Red status die max": "Máximo do dado de status Vermelho",
 "No eligible trait": "Nenhuma característica válida",
 "d8 roll": "Rolagem de d8",
 "Fixed": "Fixo",
 "Maximum Health": "Vida máxima",
 "Max": "Máx",
 "{a} icon": "Ícone de {a}",
 "The hero sheet's ICON column shows which basic actions an ability uses.": "A coluna ÍCONE da ficha de herói mostra quais ações básicas uma habilidade usa.",
 "Out": "Nocaute",
 "Principle of": "Princípio",
 "Icon": "Ícone",
 "Name": "Nome",
 "Type": "Tipo",
 "Game text": "Texto de jogo",
 "During roleplaying": "Durante a interpretação",
 "Minor twist": "Reviravolta menor",
 "Major twist": "Reviravolta maior",
 "Portrait of {name}": "Retrato de {name}",
 "your champion": "seu campeão",
 "Portrait": "Retrato",
 "Player": "Jogador",
 "Hero Name": "Nome do Herói",
 "Unnamed Champion": "Campeão sem Nome",
 "Alias": "Alcunha",
 "Physical Attributes": "Atributos Físicos",
 "Gender": "Gênero",
 "Age": "Idade",
 "Height": "Altura",
 "Eyes": "Olhos",
 "Hair": "Cabelo",
 "Skin": "Pele",
 "Build": "Porte",
 "Costume/Equipment": "Traje/Equipamento",
 "Characteristics": "Características",
 "Background": "Origem",
 "Power Source": "Fonte de Poder",
 "Archetype": "Caminho",
 "Personality": "Temperamento",
 "Hero Points": "Pontos de Herói",
 "this issue": "nesta edição",
 "Hero point {n}": "Ponto de herói {n}",
 "Rewards you can claim by spending hero points — tick them off as you use them.": "Recompensas que você resgata gastando pontos de herói. Marque cada uma conforme for usando.",
 "Hero Point Rewards": "Recompensas de Pontos de Herói",
 "+{r} reward {c}": "Recompensa +{r} nº {c}",
 "Past sessions (\"issues\") your champion took part in.": "Sessões passadas (“edições”) de que seu campeão participou.",
 "Back Issues": "Edições Anteriores",
 "Back issue {n}": "Edição anterior {n}",
 "Tick a collection when it is complete — that is when your champion advances.": "Marque uma coleção quando ela estiver completa. É nesse momento que seu campeão evolui.",
 "Collections": "Coleções",
 "Collection {n} complete": "Coleção {n} completa",
 "Collection {n}": "Coleção {n}",
 "Powers": "Poderes",
 "Die": "Dado",
 "Qualities": "Qualidades",
 "Status Dice": "Dados de Status",
 "Health Range": "Faixas de Vida",
 "Current": "Atual",
 "Current Health": "Vida atual",
 "Abilities": "Habilidades",
 "Minion forms (auxiliary sheet)": "Formas de lacaio (ficha auxiliar)",
 "Notes (auxiliary sheet)": "Biografia e notas (ficha auxiliar)",
 "The PDF library failed to load.": "A biblioteca de PDF não carregou.",
 "_hero_sheet.pdf": "_ficha_de_heroi.pdf",
 "Hero sheet PDF downloaded — hero points, collections, back issues and current Health can be clicked and typed into in any PDF reader.": "PDF da ficha baixado! Pontos de herói, coleções, edições anteriores, Vida atual, lacaios e anotações podem ser clicados e preenchidos em qualquer leitor de PDF.",
 "Could not build the PDF:": "Não foi possível gerar o PDF:",
 "Filling your hero sheet…": "Preenchendo sua ficha de herói…",
 "Note: your {zones} zone has more abilities than the sheet has rows, so the extras were combined into the last row.": "Obs.: sua zona {zones} tem mais habilidades do que linhas na ficha, então as extras foram juntadas na última linha.",
 "Could not fill the PDF:": "Não foi possível preencher o PDF:",
 "Laying out your sheet…": "Montando o layout da sua ficha…",
 "Embedding fonts…": "Incorporando as fontes…",
 "Saving…": "Salvando…",
 "Drawing page 1 of 2…": "Desenhando a página 1 de 2…",
 "Drawing page 2 of 2…": "Desenhando a página 2 de 2…",
 "Hero name": "Nome do herói",
 "Type a name, then press Enter": "Digite um nome e aperte Enter",
 "Alias / true name": "Alcunha / nome verdadeiro",
 "e.g. Kaelis Du Morne": "ex.: Kaelis Du Morne",
 "e.g. mid-thirties, or 2,000 years": "ex.: uns trinta e poucos, ou 2.000 anos",
 "e.g. glowing Hextech blue": "ex.: azul hextec brilhante",
 "e.g. sun-bronzed, bioluminescent": "ex.: bronzeada de sol, bioluminescente",
 "e.g. wiry, towering, clockwork": "ex.: franzino, imponente, mecânico",
 "Costume / equipment": "Traje / equipamento",
 "What do they wear and carry into battle?": "O que ele veste e leva para a batalha?",
 "No portrait": "Sem retrato",
 "Change portrait": "Trocar retrato",
 "Add portrait": "Adicionar retrato",
 "Remove": "Remover",
 "Goes in the picture box of the hero sheet (and the PDF).": "Vai no quadro de imagem da ficha de herói (e no PDF).",
 "Backstory notes (auxiliary sheet)": "Notas de história (ficha auxiliar)",
 "Where did they come from? Who do they fight for?": "De onde ele veio? Por quem ele luta?",
 "The rulebook asks you to rename every ability to fit your hero. The original Sentinels name stays on the sheet in small print so you and your GM can look it up.": "Dê a cada habilidade um nome que combine com seu herói e com a forma como ele luta. O Mestre sabe a regra por trás de cada uma.",
 "Leave a box empty to keep the original name.": "Deixe o campo vazio para manter o nome original.",
 "No abilities yet.": "Nenhuma habilidade ainda.",
 "Signature Weapon and Mount are meant to be renamed (e.g. \"Hextech Rifle\", \"Valor\"). You can rename any other trait too, the way the rulebook renames Power Suit to \"Power Arm\".": "A Arma e a Montaria Emblemáticas foram feitas para ganhar nome próprio (ex.: \"Rifle Hextec\", \"Valor\"). Você pode renomear qualquer outra característica também, como chamar o seu Traje Hextec de \"Manoplas Atlas\".",
 "Your hero sheet": "Sua ficha de herói",
 "Sealed — name your champion first": "Selado até você dar um nome ao seu campeão",
 "Your sheet is below, laid out like the official two-page <em>Sentinel Comics RPG</em> hero sheet. Hero points, back issues, collections and current Health can be ticked and edited right on it during play.": "Sua ficha está abaixo, em três páginas: identidade, habilidades e a ficha auxiliar com biografia, lacaios e anotações. Durante o jogo, use os botões − e + ao lado da Vida: a ficha mostra sua zona atual, acende o dado de status certo e escurece as habilidades que ainda não estão liberadas. Pontos de herói, coleções e anotações também podem ser marcados direto nela.",
 "Export PDF hero sheet": "Exportar ficha em PDF",
 "Print": "Imprimir",
 "Export JSON": "Exportar JSON",
 "Back": "Voltar",
 "Go there": "Ir para lá",
 "Welcome": "Boas-vindas",
 "How it works": "Como funciona",
 "Runeterra flavour": "Para interpretação",
 "Finishing Touches & Sheet": "Toques finais e ficha",
 "Finish the step marked “You are here” to continue": "Termine o passo marcado com “Você está aqui” para continuar",
 "Next": "Próximo",
 "<h5>Guided vs Constructed</h5>Guided: roll and choose among the allowed entries. Constructed: pick freely. Die sizes work the same either way.": "<h5>Construído ou Guiado?</h5><b>Construído:</b> escolha livremente, ideal para quem já imagina o campeão. <b>Guiado:</b> role os dados e escolha entre as opções que eles liberam (uma nova rolagem por capítulo). Os tamanhos de dado funcionam igual nos dois, e dá para trocar a qualquer momento.",
 "Method": "Método",
 "The Chronicle": "A Crônica",
 "Sealed": "Selado",
 "Unfinished": "Incompleto",
 "Complete": "Completo",
 "Complete the previous chapters first": "Complete os capítulos anteriores primeiro",
 "Champion Dossier": "Dossiê do Campeão",
 "Homeland unknown": "Terra natal desconhecida",
 "an untold legend": "uma lenda ainda não contada",
 "Source": "Fonte",
 "None yet — gained from your Source and Path.": "Nenhum ainda. Eles vêm da sua Fonte e do seu Caminho.",
 "None yet — gained from your Origin.": "Nenhuma ainda. Elas vêm da sua Origem.",
 "Greens": "Verdes",
 "Yellows": "Amarelas",
 "Reds": "Vermelhas",
 "Principles": "Princípios",
 "None yet.": "Nenhum ainda.",
 "<h5>Already bound</h5>Another die holds this trait. Unbind it there first, or choose a different trait.": "<h5>Já vinculada</h5>Outro dado já está nesta característica. Desvincule lá primeiro ou escolha outra.",
 "<h5>Not yet</h5>Finish creating your champion first — the sheet is printed from the last step.": "<h5>Ainda não</h5>Termine de criar seu campeão primeiro, pois a ficha é impressa a partir do último passo.",
 "Start over? This clears your current champion.": "Recomeçar? Isso apaga seu campeão atual.",
 "<h5>Not available with this roll</h5>Guided method: pick an entry matching one die or the sum of two dice. Use your one re-roll, or switch to the Constructed method.": "<h5>Indisponível com esta rolagem</h5>Método Guiado: escolha uma opção igual a um dado ou à soma de dois. Use sua nova rolagem ou mude para o método Construído.",
 "Not a Champion Forge file": "Não é um arquivo da Forja de Campeões",
 "Could not import:": "Não foi possível importar:",
 "Runeterra · Tabletop Chronicle": "Runeterra · Crônica de Mesa",
 "Champion Forge": "Forja de Campeões",
 "World lore": "Lore do mundo",
 "Lore": "Lore",
 "Rules cheat sheet (press ?)": "Resumo de regras (aperte ?)",
 "Rules": "Regras",
 "Export": "Exportar",
 "Import": "Importar",
 "Start over": "Recomeçar",
 "Hero Sheet": "Ficha de Herói",
 "GM Screen": "Escudo do Mestre",
  "Biography (optional)": "Biografia (opcional)",
 "Tell your champion's story. The lore guide gathers questions from your choices; click one to add it to the text.": "Conte a história do seu campeão. O guia de lore reúne perguntas a partir das suas escolhas: clique em uma para colocá-la no texto.",
 "Biography": "Biografia",
 "Where did they come from? Who do they fight for? What do they want?": "De onde ele veio? Por quem ele luta? O que ele quer?",
 "Goes on the auxiliary sheet of your hero sheet and in the PDF.": "Vai para a página 3 da ficha (a ficha auxiliar) e para o PDF.",
 "Out of the fight: only your Out action is available.": "Fora de combate: só a sua ação de Nocaute está disponível.",
 "Unlocked when your Health reaches the {z}.": "Liberada quando sua Vida chegar à {z}.",
 "Out of the fight": "Fora de combate",
 "Adjust Health": "Ajustar Vida",
 "Lose 1 Health": "Perder 1 de Vida",
 "Recover 1 Health": "Recuperar 1 de Vida",
 "Back to full Health": "Voltar à Vida cheia",
 "Forms and modes": "Formas e modos",
 "Table notes": "Anotações da mesa",
 "Minion forms": "Formas de lacaio",
 "Power": "Poder",
 "Ability": "Habilidade",
 "Full rewrite": "Reescrita",
 "Swap": "Trocar",
 "For": "Por",
 "The new trait keeps the {die}, and every ability that used {old} now uses it.": "A nova característica fica com o mesmo {die}, e toda habilidade que usava {old} passa a usá-la.",
 "Energy or element": "Energia ou elemento",
 "e.g. fire, Hextech, shadow": "ex.: fogo, Hextec, sombra",
 "No other ability of this colour, from the same list, fits the same power or quality.": "Nenhuma outra habilidade dessa cor, da mesma lista, funciona com o mesmo poder ou qualidade.",
 "Evolve your champion": "Evoluir campeão",
 "Every six back issues become a collection, and a collection closes a storyline. Between collections your champion can change. Pick the size of the change:": "A cada seis edições anteriores você fecha uma coleção, e cada coleção encerra um arco da história. Entre uma coleção e outra, seu campeão pode mudar. Escolha o tamanho da mudança:",
 "Cosmetic changes": "Mudança de visual",
 "New look, alias, costume or name: edit them in the Legend chapter of the Forge. No rules involved.": "Novo visual, alcunha, traje ou nome: edite no capítulo Lenda da Forja, sem regra nenhuma envolvida.",
 "Your sheet has its own page": "Sua ficha tem uma página própria",
 "Full screen, with the Health tracker always at hand for play and the Evolve your champion tools.": "Em tela cheia, com o controle de Vida sempre à mão durante o jogo e as ferramentas de Evoluir campeão.",
 "Open the sheet": "Abrir a ficha",
 "Only your Out action is available.": "Só a sua ação de Nocaute está disponível.",
 "Abilities above your zone are dimmed on the sheet.": "Habilidades acima da sua zona ficam escurecidas na ficha.",
 "Sheet pages": "Páginas da ficha",
 "Identity and principles": "Identidade e princípios",
 "Powers and abilities": "Poderes e habilidades",
 "Auxiliary sheet": "Ficha auxiliar",
 "Edit in the Forge": "Editar na Forja",
 "Your sheet is not ready yet": "Sua ficha ainda não está pronta",
 "Finish creating your champion in the Forge (the last chapter asks for a name) and the complete sheet appears here.": "Termine de criar seu campeão na Forja (o último capítulo pede um nome) e a ficha completa aparece aqui.",
 "Go to the Forge": "Ir para a Forja",
 "Champion at the table": "Campeão na mesa",
 "Sheet": "Ficha",
 "Guide": "Guia",
 "Got it": "Entendi",
 "Turn the guide off": "Não mostrar mais o guia",
 "used by {ab}": "já usado em {ab}",
 "you already have {die}": "você já tem {die}",
 "<h5>Not available</h5>You already have this trait here, so this die would be wasted. Choose a different trait, or unbind it where it is first.": "<h5>Indisponível</h5>Você já tem esta característica aqui, então este dado seria desperdiçado. Escolha outra, ou solte o dado onde ela está antes.",
 "Grows under pressure": "Cresce sob pressão",
 "Starts modest and becomes more dangerous as the fight goes badly.": "Começa modesto e fica mais perigoso quando a luta aperta.",
 "Strong from the start": "Forte no começo",
 "Hits hard while things are calm and gets shakier under pressure.": "Bate forte enquanto está tudo bem e fica mais frágil sob pressão.",
 "Steady": "Constante",
 "The same die in every zone: reliable from start to finish.": "O mesmo dado em todas as zonas: confiável do começo ao fim.",
 "What are these three dice?": "Para que servem esses três dados?",
 "They are your <b>status dice</b>. Every roll uses one of them, together with a power and a quality. Which one depends on your zone: <b>Green</b> while you are fine, <b>Yellow</b> when you start to get hurt (or the scene heats up) and <b>Red</b> when you are hanging by a thread.": "São os seus <b>dados de status</b>. Toda rolagem usa um deles, junto com um poder e uma qualidade. Qual deles depende da sua zona: o <b>Verde</b> enquanto você está inteiro, o <b>Amarelo</b> quando começa a se machucar (ou a cena esquenta) e o <b>Vermelho</b> quando está por um fio.",
 "How to choose": "Como escolher",
 "<b>Growing dice</b> (d6, d8, d10) start modest and shine when things go badly. <b>Equal dice</b> are steady. <b>Shrinking dice</b> (d10, d8, d6) are strong early and weaker under pressure. Your <b>Red</b> die also adds to your maximum Health, and each Temperament gives an <b>Out</b> ability for when you are knocked out.": "<b>Dados que crescem</b> (d6, d8, d10) começam modestos e brilham quando tudo dá errado. <b>Dados iguais</b> são constantes. <b>Dados que diminuem</b> (d10, d8, d6) são fortes no começo e mais fracos sob pressão. O dado <b>Vermelho</b> também soma na sua Vida máxima, e cada Temperamento dá uma habilidade de <b>Nocaute</b> para quando você cai.",
 "People": "Povo",
 "of {n}": "de {n}",
 "Choose your people": "Escolha o seu povo",
 "Choose a people.": "Escolha um povo.",
 "Click the people your champion belongs to. Hover a card to preview it.": "Clique no <b>povo</b> do seu campeão. Passe o mouse num cartão para ver os detalhes.",
 "Suits a champion of the {people} people": "Combina com um campeão do povo {people}",
 "Fitting Homelands": "Terras Natais que combinam",
 "Fitting Paths": "Caminhos que combinam",
 "Read about the peoples of Runeterra": "Ler sobre os povos de Runeterra",
 "Runeterra is home to many peoples. Your people is pure flavour: it changes no rule, but suggests homelands and choices that suit it.": "Runeterra abriga muitos povos. O seu povo serve só para a interpretação: não muda nenhuma regra, mas sugere terras natais e escolhas que combinam com ele.",
 "What does your people think of you, and what do you think of them?": "O que o seu povo pensa de você, e o que você pensa dele?",
 "Which custom of your people do you still keep, even far from home?": "Que costume do seu povo você ainda mantém, mesmo longe de casa?",
 "The world, its regions and peoples": "O mundo, suas regiões e povos",
 "The table summary, key ?": "O resumo para a mesa, tecla ?",
 "Your finished champion, full screen": "Seu campeão pronto, em tela cheia",
 "roll and sort": "role e ordene",
 "Min": "Mín",
 "Mid": "Médio",
 "Status": "Status",
 "The <b>Mid</b> die is the effect die, unless an ability says otherwise.": "O dado <b>Médio</b> é o dado de efeito, a não ser que uma habilidade diga outra coisa.",
 "The chapters are listed in the chronicle: each one opens once the previous is complete.": "Os capítulos ficam na crônica: cada um se abre quando o anterior estiver completo.",
 "Change details": "Mudar detalhes",
 "Swap one power or quality for another of the same die, one principle for another, or one ability for another of the same colour. Use the form below.": "Troque um poder ou qualidade por outro com o mesmo dado, um princípio por outro, ou uma habilidade por outra da mesma cor. Use o formulário abaixo.",
 "Major rewrite": "Reescrever tudo",
 "When too much changed, go through creation again with the Constructed method, keeping the champion's history.": "Quando muita coisa mudou, refaça a criação pelo método Construído, mantendo a história do campeão.",
 "What to change": "O que mudar",
 "Apply change": "Aplicar mudança",
 "Recorded under the collection “{c}”.": "Fica registrada na coleção “{c}”.",
 "Change history": "Histórico de mudanças",
 "The champion was rewritten from scratch.": "O campeão foi reescrito do zero.",
 "Undo last change": "Desfazer a última mudança",
 "No changes yet. They also appear on page 3 of the sheet.": "Nenhuma mudança ainda. Elas também aparecem na página 3 da ficha.",
 "Starts the chapters again from the Origin with the Constructed method. Name, description, portrait, biography, collections, back issues, notes and this history stay.": "Recomeça os capítulos a partir da Origem, pelo método Construído. Nome, descrição, retrato, biografia, coleções, edições anteriores, anotações e este histórico continuam.",
 "Rewrite champion": "Reescrever campeão",
 "Rewrite the champion? You go through creation again with the Constructed method. Name, description, portrait, biography, collections, back issues, notes and the change history are kept.": "Reescrever o campeão? Você refaz a criação pelo método Construído. Nome, descrição, retrato, biografia, coleções, edições anteriores, anotações e o histórico de mudanças são mantidos.",
 "Changes made between collections (Sheet page, “Evolve your champion” tab).": "Mudanças feitas entre coleções (página Ficha, aba “Evoluir campeão”).",
 "Evolution": "Evolução",
 "Note line {n}": "Linha de anotação {n}",
 "Lore guide": "Guia de lore",
 "Read in the Lore": "Ler na Lore",
 "Which of these champions does your hero know, admire or fear? {c}.": "Qual destes campeões seu herói conhece, admira ou teme? {c}.",
 "What from that life do you still carry, and who did you leave behind?": "O que dessa vida você ainda carrega, e quem ficou para trás?",
 "Who from those days would recognise you today?": "Quem daquela época ainda te reconheceria hoje?",
 "When did this power first show itself, and what did it cost you?": "Quando esse poder se manifestou pela primeira vez, e quanto ele te custou?",
 "Who else knows where your power comes from?": "Quem mais sabe de onde vem o seu poder?",
 "Who taught you to fight like this?": "Quem te ensinou a lutar desse jeito?",
 "What was the first fight you could not win?": "Qual foi a primeira luta que você não conseguiu vencer?",
 "Where does this way of being come from?": "De onde vem esse seu jeito de ser?",
 "Who clashes with you, or is won over, because of it?": "Quem se irrita com você, ou se encanta, por causa dele?",
 "Principle": "Princípio",
 "The campaign": "A campanha",
 "The present day (994 DN)": "Os tempos atuais (994 DN)",
 "The story of the table starts now, in times of political unrest, returning gods and global threats.": "A história da mesa começa agora, em tempos de agitação política, deuses que retornam e ameaças globais.",
 "Where is your hero when the campaign begins, and why?": "Onde seu herói está quando a campanha começa, e por quê?",
 "What do they want that they cannot get alone?": "O que ele quer e não consegue alcançar sozinho?",
 "Change choice": "Trocar escolha",
 "Keep the current choice": "Manter a escolha atual",
 "Change last choice": "Trocar última escolha",
 "<b>Which one?</b> Constructed is the most direct: you choose everything, ideal when you already have a champion in mind or are new to the game. Guided is for those who like surprises: at each chapter you roll the dice and pick among the options they unlock, with one re-roll per chapter.": "<b>Qual escolher?</b> Construído é o mais direto: você escolhe tudo, ideal quando já tem um campeão em mente ou está começando no jogo. Guiado é para quem gosta de surpresa: a cada capítulo você rola os dados e escolhe entre as opções que eles liberam, podendo rolar de novo uma vez por capítulo.",
 "FOOTER": "Projeto de fã não oficial. Runeterra e League of Legends são © Riot Games. Uso pessoal e não comercial."
});
