#!/usr/bin/env node
/* Seal the GM page: encrypts gm/content.html into js/gm-vault.js.

   The site is static (GitHub Pages), so nothing on a server can check a password. Instead the
   GM content is published only as AES-256-GCM ciphertext, with the key derived from the password
   (PBKDF2-SHA256). gm.html asks for the password and decrypts in the browser; a wrong password
   simply fails to decrypt. Neither the password nor the plain content is ever committed.

   Usage:  GM_PASSWORD='…' node tools/gm-seal.js [content.html]
           (without GM_PASSWORD it asks for it on the terminal)
   gm/content.html is git-ignored: keep your GM notes there and re-run this after every edit. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const SRC = path.resolve(process.argv[2] || path.join(ROOT, 'gm', 'content.html'));
const OUT = path.join(ROOT, 'js', 'gm-vault.js');
const ITER = 310000;

const ask = q => new Promise(res => {
  const rl = require('readline').createInterface({ input: process.stdin, output: process.stdout });
  rl.question(q, a => { rl.close(); res(a); });
});

(async () => {
  const password = process.env.GM_PASSWORD || await ask('GM password: ');
  if (!password) { console.error('No password given.'); process.exit(1); }
  const html = fs.existsSync(SRC) ? fs.readFileSync(SRC, 'utf8') : '';
  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const key = crypto.pbkdf2Sync(password.normalize('NFC'), salt, ITER, 32, 'sha256');
  const c = crypto.createCipheriv('aes-256-gcm', key, iv);
  // WebCrypto expects ciphertext followed by the 16-byte tag.
  const ct = Buffer.concat([c.update(html, 'utf8'), c.final(), c.getAuthTag()]);
  const vault = { v: 1, kdf: 'PBKDF2-SHA256', iter: ITER, salt: salt.toString('base64'), iv: iv.toString('base64'), ct: ct.toString('base64') };
  fs.writeFileSync(OUT, '/* Generated by tools/gm-seal.js — encrypted GM content. Do not edit by hand. */\n' +
    `window.GM_VAULT = ${JSON.stringify(vault)};\n`);
  console.log(`Sealed ${fs.existsSync(SRC) ? path.relative(ROOT, SRC) : '(empty page)'} → ${path.relative(ROOT, OUT)} (${html.length} chars)`);
})();
