#!/usr/bin/env node
/* Seal the GM material: encrypts everything only the Game Master may read into js/gm-vault.js.

   The site is static (GitHub Pages), so nothing on a server can check a password. Instead the GM material
   is published only as AES-256-GCM ciphertext, with the key derived from the password (PBKDF2-SHA256).
   gm.html and antagonista.html ask for the password (or use the key the Screen keeps for the tab) and decrypt
   in the browser; a wrong password simply fails to decrypt. Neither the password nor the plain material is
   ever committed: everything under gm/ is git-ignored.

   What goes in the vault (version 2):
     gm/content.html     optional HTML for the Screen's own notes page;
     gm/src/<name>.js    the GM-only modules, run in the browser after unlocking, in this order:
                         gm-flavour, gm-twists, gm-tools, gm-villain-data, gm-env-data, gm-bullpen.

   Usage:  GM_PASSWORD='…' node tools/gm-seal.js
           (without GM_PASSWORD it asks for it on the terminal)
   To edit the sealed material: GM_PASSWORD='…' node tools/gm-unseal.js (writes gm/), edit, then seal again. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const GM = path.join(ROOT, 'gm');
const OUT = path.join(ROOT, 'js', 'gm-vault.js');
const ORDER = ['gm-flavour', 'gm-twists', 'gm-tools', 'gm-villain-data', 'gm-env-data', 'gm-bullpen'];
const ITER = 310000;

const ask = q => new Promise(res => {
  const rl = require('readline').createInterface({ input: process.stdin, output: process.stdout });
  rl.question(q, a => { rl.close(); res(a); });
});

(async () => {
  const password = process.env.GM_PASSWORD || await ask('GM password: ');
  if (!password) { console.error('No password given.'); process.exit(1); }
  const htmlFile = path.join(GM, 'content.html');
  const modules = {};
  for (const n of ORDER) {
    const f = path.join(GM, 'src', n + '.js');
    if (fs.existsSync(f)) modules[n] = fs.readFileSync(f, 'utf8');
    else console.warn(`warning: gm/src/${n}.js not found, it will not be in the vault`);
  }
  const payload = { v: 2, html: fs.existsSync(htmlFile) ? fs.readFileSync(htmlFile, 'utf8') : '', modules };
  const plain = JSON.stringify(payload);
  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const key = crypto.pbkdf2Sync(password.normalize('NFC'), salt, ITER, 32, 'sha256');
  const c = crypto.createCipheriv('aes-256-gcm', key, iv);
  // WebCrypto expects ciphertext followed by the 16-byte tag.
  const ct = Buffer.concat([c.update(plain, 'utf8'), c.final(), c.getAuthTag()]);
  const vault = { v: 1, kdf: 'PBKDF2-SHA256', iter: ITER, salt: salt.toString('base64'), iv: iv.toString('base64'), ct: ct.toString('base64') };
  fs.writeFileSync(OUT, '/* Generated by tools/gm-seal.js — encrypted GM material. Do not edit by hand. */\n' +
    `window.GM_VAULT = ${JSON.stringify(vault)};\n`);
  console.log(`Sealed ${Object.keys(modules).length} modules${payload.html ? ' and the notes page' : ''} → ${path.relative(ROOT, OUT)} (${(plain.length / 1024).toFixed(0)} KB)`);
})();
